// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -2; // objPlayerMouse
global.__objectDepths[1] = -2; // objPlayerMouseHouse
global.__objectDepths[2] = -2; // objPlayerShieldMouse
global.__objectDepths[3] = 0; // objMaskMenu
global.__objectDepths[4] = -3; // objPlayerCarEnter
global.__objectDepths[5] = -1; // objPlayerHospital
global.__objectDepths[6] = 1; // objMaskDrop
global.__objectDepths[7] = 2; // objPlayerDead
global.__objectDepths[8] = 0; // objPlayerBombDead
global.__objectDepths[9] = 0; // objPlayerOpenWindow
global.__objectDepths[10] = -1; // objPWalkWindow
global.__objectDepths[11] = -1; // objPlayerEnterWindow
global.__objectDepths[12] = 0; // objPVomit
global.__objectDepths[13] = 0; // objVomit
global.__objectDepths[14] = 0; // objPlayerTurning
global.__objectDepths[15] = 0; // objPlayerRipTape
global.__objectDepths[16] = 0; // objPoliceTape
global.__objectDepths[17] = 0; // objPoliceTapeRipped
global.__objectDepths[18] = 0; // objClubOwner
global.__objectDepths[19] = 0; // objPKillOwner
global.__objectDepths[20] = 0; // objPlayerOpenGrate
global.__objectDepths[21] = 0; // objPlayerClimbDown
global.__objectDepths[22] = 0; // objPlayerClimbUp
global.__objectDepths[23] = 0; // objEnemyBash
global.__objectDepths[24] = 0; // objPAttackThroat
global.__objectDepths[25] = 0; // objEnemyHeadKick
global.__objectDepths[26] = 0; // objPBrickKill
global.__objectDepths[27] = 0; // objPAttackSnap
global.__objectDepths[28] = 0; // objPBluntKill
global.__objectDepths[29] = 0; // objPAxeKill
global.__objectDepths[30] = 0; // objPScissorKill
global.__objectDepths[31] = 0; // objPSwordKill
global.__objectDepths[32] = 0; // objPKnifeKill
global.__objectDepths[33] = 0; // objPPoolKill
global.__objectDepths[34] = 0; // objPBrokenPoolKill
global.__objectDepths[35] = 0; // objPClubBoss2
global.__objectDepths[36] = 0; // objPHoboBash
global.__objectDepths[37] = 0; // objPHoboBlunt
global.__objectDepths[38] = 0; // objPBodyguardBlunt
global.__objectDepths[39] = 0; // objPBodyguardBash
global.__objectDepths[40] = 0; // objPDrillKill
global.__objectDepths[41] = 0; // objPSledgeKill
global.__objectDepths[42] = 0; // objPMacheteKill
global.__objectDepths[43] = 0; // objPBottleKill
global.__objectDepths[44] = 0; // objPDartKill
global.__objectDepths[45] = 0; // objPBoilingPotKill
global.__objectDepths[46] = 0; // objPKillBodyguard
global.__objectDepths[47] = 0; // objPHammerKill
global.__objectDepths[48] = -2; // objPlayerBiker
global.__objectDepths[49] = -2; // objPlayerBikerHouse
global.__objectDepths[50] = 0; // objMCBike
global.__objectDepths[51] = 1; // objMCHelmet
global.__objectDepths[52] = 0; // objThrowingKnife
global.__objectDepths[53] = 0; // objMCBartender
global.__objectDepths[54] = 0; // objBartender
global.__objectDepths[55] = 0; // objBikerSushi
global.__objectDepths[56] = 0; // objSushiGuy
global.__objectDepths[57] = 0; // objPlayerKneel
global.__objectDepths[58] = -1; // objPlayerBikerKick
global.__objectDepths[59] = 0; // objBikerClimbDown
global.__objectDepths[60] = 0; // objBikerClimbUp
global.__objectDepths[61] = -1; // objBikeEnding
global.__objectDepths[62] = 0; // objPalmTreeTop
global.__objectDepths[63] = 0; // objBikerKillJonatan
global.__objectDepths[64] = -1; // objPlayerBikerHack
global.__objectDepths[65] = 0; // objMCStompKill
global.__objectDepths[66] = 0; // objMCChopKill
global.__objectDepths[67] = 0; // objMCKnifeKill
global.__objectDepths[68] = -1; // objPigButcher
global.__objectDepths[69] = 0; // objPigButcherHeadbutt
global.__objectDepths[70] = 0; // objPigButcherKill
global.__objectDepths[71] = -10000; // objEffector
global.__objectDepths[72] = -10000; // objEffectorHouse
global.__objectDepths[73] = -10000; // objEffectorHospital
global.__objectDepths[74] = -10000; // objEffectorInstant
global.__objectDepths[75] = 3; // objSurfacer
global.__objectDepths[76] = 9999999; // objBackgroundColor
global.__objectDepths[77] = 9999999; // objBackgroundColorClear
global.__objectDepths[78] = -1; // objPlayer
global.__objectDepths[79] = 0; // objDoorV
global.__objectDepths[80] = 0; // objDoorH
global.__objectDepths[81] = 0; // objDoorV2
global.__objectDepths[82] = 0; // objDoorH2
global.__objectDepths[83] = -3; // objHospitalEntranceDoors
global.__objectDepths[84] = -10; // objWallHeavyV
global.__objectDepths[85] = -10; // objWallHeavyH
global.__objectDepths[86] = -10; // objWallSoftV
global.__objectDepths[87] = -10; // objWallSoftH
global.__objectDepths[88] = -10; // objSewerWallV
global.__objectDepths[89] = -10; // objSewerWallH
global.__objectDepths[90] = -10; // objCellWallV
global.__objectDepths[91] = -10; // objCellWallH
global.__objectDepths[92] = -10; // objWallBrickV
global.__objectDepths[93] = -10; // objWallBrickH
global.__objectDepths[94] = -10; // objWallHospitalV
global.__objectDepths[95] = -10; // objWallHospitalH
global.__objectDepths[96] = 0; // objGlassPanelV
global.__objectDepths[97] = 0; // objGlassPanelVBroken
global.__objectDepths[98] = 0; // objGlassPanelH
global.__objectDepths[99] = 0; // objGlassPanelHBroken
global.__objectDepths[100] = 0; // objWindowV
global.__objectDepths[101] = 0; // objWindowH
global.__objectDepths[102] = 0; // objRailV
global.__objectDepths[103] = 0; // objRailH
global.__objectDepths[104] = 0; // objWoodFenceV
global.__objectDepths[105] = 0; // objWoodFenceH
global.__objectDepths[106] = 0; // objBalconyV
global.__objectDepths[107] = 0; // objBalconyH
global.__objectDepths[108] = 0; // objHorBarrier
global.__objectDepths[109] = 0; // objVertBarrier
global.__objectDepths[110] = 0; // objSolid
global.__objectDepths[111] = -10; // objCorner
global.__objectDepths[112] = 0; // objTransitioner
global.__objectDepths[113] = 3; // objElevator
global.__objectDepths[114] = -1; // objPolice
global.__objectDepths[115] = -1; // objPolicePatrol
global.__objectDepths[116] = -1; // objPoliceStationary
global.__objectDepths[117] = -1; // objPoliceMelee
global.__objectDepths[118] = -1; // objPoliceMeleeStationary
global.__objectDepths[119] = -1; // objInspector
global.__objectDepths[120] = 0; // objChief
global.__objectDepths[121] = 1; // objPoliceHat
global.__objectDepths[122] = -1; // objFatmanEating
global.__objectDepths[123] = -1; // objFatmanTelephone
global.__objectDepths[124] = 0; // objFatmanShit
global.__objectDepths[125] = 0; // objWaiter
global.__objectDepths[126] = 0; // objWaiterStationary
global.__objectDepths[127] = 0; // objEnemyIdlePee
global.__objectDepths[128] = 0; // objEnemyIdleSmoke
global.__objectDepths[129] = 0; // objEnemySit
global.__objectDepths[130] = 0; // objEnemyIdleGuard
global.__objectDepths[131] = 0; // objEnemySitDrink
global.__objectDepths[132] = 0; // objEnemyDrink
global.__objectDepths[133] = 0; // objEnemyPhone
global.__objectDepths[134] = 1; // objCellPhone
global.__objectDepths[135] = 0; // objEnemyIdle
global.__objectDepths[136] = -1; // objEnemy
global.__objectDepths[137] = -1; // objEnemyPatrol
global.__objectDepths[138] = -1; // objEnemyStationary
global.__objectDepths[139] = -1; // objEnemyMelee
global.__objectDepths[140] = -1; // objEnemyMeleeStationary
global.__objectDepths[141] = 0; // objEHideM16
global.__objectDepths[142] = -1; // objDogPatrol
global.__objectDepths[143] = -1; // objEnemyFat
global.__objectDepths[144] = 1; // objKnockedOut
global.__objectDepths[145] = 2; // objDeadBody
global.__objectDepths[146] = 2; // objBodyPart
global.__objectDepths[147] = 0; // objECrawl
global.__objectDepths[148] = 1; // objDogBite
global.__objectDepths[149] = -1; // objESubwayStatic
global.__objectDepths[150] = 1; // objSubwayKnockedOut
global.__objectDepths[151] = 0; // objEGiveUp
global.__objectDepths[152] = 1; // objBox
global.__objectDepths[153] = 2; // objOpenedBox
global.__objectDepths[154] = 0; // objDumpster
global.__objectDepths[155] = 0; // objInvestigationFileSpread
global.__objectDepths[156] = -1; // objPlayerForm
global.__objectDepths[157] = -1; // objMCForm
global.__objectDepths[158] = -1; // objBedClip
global.__objectDepths[159] = -1; // objKitchenShelfClip
global.__objectDepths[160] = -1; // objLivingRoomClip1
global.__objectDepths[161] = -1; // objLivingRoomClip2
global.__objectDepths[162] = -1; // objTableClip
global.__objectDepths[163] = -1; // objKitchenCounterClip1
global.__objectDepths[164] = -1; // objKitchenCounterClip3
global.__objectDepths[165] = -1; // objKitchenCounterClip2
global.__objectDepths[166] = 1; // objBriefcase
global.__objectDepths[167] = -1; // objVHSTake
global.__objectDepths[168] = -1; // objPizzaTake
global.__objectDepths[169] = -1; // objDrink
global.__objectDepths[170] = -1; // objSixpack
global.__objectDepths[171] = -1; // objChipsBag
global.__objectDepths[172] = -1; // objKeys
global.__objectDepths[173] = 1; // objPlayerJacket
global.__objectDepths[174] = 1; // objPlayerPants
global.__objectDepths[175] = 0; // objToken
global.__objectDepths[176] = 1; // objSecretMask
global.__objectDepths[177] = 1; // objWeapon
global.__objectDepths[178] = -1; // objSpecificWeapon
global.__objectDepths[179] = 0; // objWeaponThrow
global.__objectDepths[180] = -2; // objThrowingWeapon
global.__objectDepths[181] = -2; // objBullet
global.__objectDepths[182] = -2; // objEBullet
global.__objectDepths[183] = 0; // objBulletHit
global.__objectDepths[184] = 0; // objBloodDrop2
global.__objectDepths[185] = 0; // objBloodCut
global.__objectDepths[186] = 0; // objBloodHit
global.__objectDepths[187] = 0; // objBloodSmoke2
global.__objectDepths[188] = 2; // objBloodSplat2
global.__objectDepths[189] = 1; // objBrains2
global.__objectDepths[190] = 1; // objBrainChunk2
global.__objectDepths[191] = 1; // objGuts2
global.__objectDepths[192] = 1; // objSkinPiece2
global.__objectDepths[193] = 0; // objBloodSmoke
global.__objectDepths[194] = 2; // objBloodSplat
global.__objectDepths[195] = 0; // objBloodDrop
global.__objectDepths[196] = 3; // objBloodPool
global.__objectDepths[197] = 0; // objBloodSquirt
global.__objectDepths[198] = 0; // objBrains
global.__objectDepths[199] = -9; // objHit
global.__objectDepths[200] = -9; // objSmokeHit
global.__objectDepths[201] = 0; // objShell
global.__objectDepths[202] = 0; // objDebris
global.__objectDepths[203] = 0; // objShard
global.__objectDepths[204] = 0; // objTinyShard
global.__objectDepths[205] = 0; // objFlies
global.__objectDepths[206] = -9; // objSteam
global.__objectDepths[207] = 0; // objPWater
global.__objectDepths[208] = -17; // objSpark2
global.__objectDepths[209] = -1; // objSpark1
global.__objectDepths[210] = 3; // objBombGround
global.__objectDepths[211] = 0; // objFloatingBottle
global.__objectDepths[212] = 0; // objClip
global.__objectDepths[213] = 0; // objDriveSmoke
global.__objectDepths[214] = 1; // objBrokenBottle
global.__objectDepths[215] = 0; // objTitle
global.__objectDepths[216] = 0; // objPalmTree
global.__objectDepths[217] = 0; // objHouse
global.__objectDepths[218] = 0; // objLevelSelect
global.__objectDepths[219] = 0; // objShowControls
global.__objectDepths[220] = 0; // objPause
global.__objectDepths[221] = -101; // objScore
global.__objectDepths[222] = -10001; // objLevelComplete
global.__objectDepths[223] = 0; // objMaskUnlock
global.__objectDepths[224] = 0; // objWeaponUnlock
global.__objectDepths[225] = 0; // objLevelTitle
global.__objectDepths[226] = 0; // objMCLevelTitle
global.__objectDepths[227] = 0; // objHospitalTitle
global.__objectDepths[228] = 0; // objPartTitle
global.__objectDepths[229] = 0; // objInterlude
global.__objectDepths[230] = 0; // objBandCredits
global.__objectDepths[231] = 0; // objWave
global.__objectDepths[232] = 0; // objCredits
global.__objectDepths[233] = 0; // objSpread
global.__objectDepths[234] = -100; // objLightingEngine
global.__objectDepths[235] = 0; // objLight
global.__objectDepths[236] = -100; // objLightingNormal
global.__objectDepths[237] = 0; // objLightNormal
global.__objectDepths[238] = -1; // objLetterSocket
global.__objectDepths[239] = -2; // objLetter
global.__objectDepths[240] = -10; // objPuzzle
global.__objectDepths[241] = -3; // objLetterDone
global.__objectDepths[242] = -10001; // objLetterFound
global.__objectDepths[243] = 0; // objScanlines
global.__objectDepths[244] = 10; // objShadowH
global.__objectDepths[245] = 10; // objShadowV
global.__objectDepths[246] = 0; // objShootThrough
global.__objectDepths[247] = 0; // objFurniture
global.__objectDepths[248] = 0; // objPhoneConversation
global.__objectDepths[249] = 2; // objSurfaceReturn
global.__objectDepths[250] = 0; // objTeleporter
global.__objectDepths[251] = 0; // objScoreStats
global.__objectDepths[252] = 0; // objBoss
global.__objectDepths[253] = 0; // objHouseReturn
global.__objectDepths[254] = -10001; // objCheckpoint
global.__objectDepths[255] = 0; // objExporter
global.__objectDepths[256] = 0; // objTrainshake
global.__objectDepths[257] = -1; // objElectricLight
global.__objectDepths[258] = 0; // objHospitalTransition
global.__objectDepths[259] = 0; // objHospitalTalk
global.__objectDepths[260] = -100000; // objDizzy
global.__objectDepths[261] = 0; // objEmpty
global.__objectDepths[262] = 0; // objMiscEnemy
global.__objectDepths[263] = 0; // objFlameParticle
global.__objectDepths[264] = 0; // objBoss3Spawn
global.__objectDepths[265] = -100; // objSequence12Light
global.__objectDepths[266] = -100; // objTutorialLight
global.__objectDepths[267] = 0; // objGoToCar
global.__objectDepths[268] = 0; // objScoreDetails
global.__objectDepths[269] = 0; // objSunSparkle
global.__objectDepths[270] = 0; // objDateRewind
global.__objectDepths[271] = -1000; // objFinalDialogue
global.__objectDepths[272] = -1000; // objFinalDialogue2
global.__objectDepths[273] = 0; // objAlienWare
global.__objectDepths[274] = 0; // objSteamQuestion
global.__objectDepths[275] = 0; // objFocus
global.__objectDepths[276] = 0; // objTub
global.__objectDepths[277] = 1; // objSink
global.__objectDepths[278] = 0; // objUrinalV
global.__objectDepths[279] = 1; // objToilet
global.__objectDepths[280] = -10; // objShowerCurtain
global.__objectDepths[281] = 0; // objJacuzzi
global.__objectDepths[282] = 0; // objShowerGlassV
global.__objectDepths[283] = 0; // objShowerGlassH
global.__objectDepths[284] = 0; // objShowerGlassDoor
global.__objectDepths[285] = 0; // objHotelSuiteTub
global.__objectDepths[286] = 0; // objHotelSink
global.__objectDepths[287] = 1; // objHotelSuiteToilet
global.__objectDepths[288] = 1; // objChair
global.__objectDepths[289] = 0; // objShelves
global.__objectDepths[290] = 0; // objKitchenSink
global.__objectDepths[291] = 0; // objStove
global.__objectDepths[292] = 1; // objTable
global.__objectDepths[293] = 0; // objMicrowave
global.__objectDepths[294] = 0; // objFridge
global.__objectDepths[295] = 0; // objToyBall
global.__objectDepths[296] = 0; // objToyTurtle
global.__objectDepths[297] = 0; // objToyBear
global.__objectDepths[298] = 0; // objToyLego
global.__objectDepths[299] = 2; // objToyM16
global.__objectDepths[300] = 2; // objToyMP5
global.__objectDepths[301] = 0; // objPelletsCorner
global.__objectDepths[302] = 0; // objPelletsSide
global.__objectDepths[303] = 0; // objPellets
global.__objectDepths[304] = -3; // objPelletPlant
global.__objectDepths[305] = -1; // objPlant
global.__objectDepths[306] = -3; // objHospitalPlant
global.__objectDepths[307] = 1; // objPizza
global.__objectDepths[308] = 1; // objTrashbag
global.__objectDepths[309] = 1; // objTrashcan
global.__objectDepths[310] = 1; // objBurningTrashcan
global.__objectDepths[311] = 0; // objHomelessBed
global.__objectDepths[312] = 1; // objSofaV64
global.__objectDepths[313] = 1; // objSofaV48
global.__objectDepths[314] = 1; // objSofaH64
global.__objectDepths[315] = 0; // objDrawerV24
global.__objectDepths[316] = 0; // objDrawerH24
global.__objectDepths[317] = 1; // objSofaH48
global.__objectDepths[318] = 10; // objShirts
global.__objectDepths[319] = -1; // objCassetteDeck
global.__objectDepths[320] = -1; // objComputer
global.__objectDepths[321] = 0; // objVinylRecord
global.__objectDepths[322] = 0; // objBigTable
global.__objectDepths[323] = 0; // objBeds
global.__objectDepths[324] = -1; // objLamps
global.__objectDepths[325] = 10; // objJackets
global.__objectDepths[326] = 0; // objNes
global.__objectDepths[327] = -1; // objVinylPlayer
global.__objectDepths[328] = 0; // objSpeaker
global.__objectDepths[329] = -1; // objTVBlack
global.__objectDepths[330] = 10; // objTigerCarpet
global.__objectDepths[331] = 0; // objFountain
global.__objectDepths[332] = 0; // objBigBed
global.__objectDepths[333] = 1; // objLeatherCouch
global.__objectDepths[334] = 0; // objPoolTable
global.__objectDepths[335] = 0; // objGlassTable
global.__objectDepths[336] = 0; // objNightStand
global.__objectDepths[337] = -4; // objTrophyHead
global.__objectDepths[338] = 1; // objWineRack
global.__objectDepths[339] = 0; // objCouchCushion
global.__objectDepths[340] = 1; // objArmchair
global.__objectDepths[341] = 0; // objRichTable
global.__objectDepths[342] = 1; // objDiningChair
global.__objectDepths[343] = 1; // objLaundryBasket
global.__objectDepths[344] = 3; // objCarBottom
global.__objectDepths[345] = 0; // objAquarium
global.__objectDepths[346] = 1; // objAquariumBreak
global.__objectDepths[347] = 3; // objAquariumWater
global.__objectDepths[348] = -1; // objPhone
global.__objectDepths[349] = -2; // objVendingMachine
global.__objectDepths[350] = -4; // objTVWallMounted
global.__objectDepths[351] = 0; // objLockerH
global.__objectDepths[352] = 0; // objLockerV
global.__objectDepths[353] = 1; // objSubwayBenchV
global.__objectDepths[354] = 1; // objSubwayBench
global.__objectDepths[355] = -3; // objTrain
global.__objectDepths[356] = -4; // objSubwayDoor
global.__objectDepths[357] = -4; // objClotheslineH
global.__objectDepths[358] = -4; // objClotheslineV
global.__objectDepths[359] = 0; // objAnsweringMachine
global.__objectDepths[360] = 0; // objPlayerBed1
global.__objectDepths[361] = 0; // objPlayerBed2
global.__objectDepths[362] = 1; // objPlayerCouch
global.__objectDepths[363] = 0; // objPlayerKitchenCounter
global.__objectDepths[364] = 0; // objPlayerKitchenShelf
global.__objectDepths[365] = 0; // objPlayerKitchenSink
global.__objectDepths[366] = 0; // objPlayerLivingRoomTable
global.__objectDepths[367] = 0; // objPlayerFridge
global.__objectDepths[368] = 0; // objPlayerTable
global.__objectDepths[369] = 1; // objVomitBucket
global.__objectDepths[370] = 0; // objPlayerTub
global.__objectDepths[371] = 0; // objGate
global.__objectDepths[372] = 1; // objMonitors
global.__objectDepths[373] = 1; // objPornBed
global.__objectDepths[374] = 0; // objPornCamera
global.__objectDepths[375] = -1; // objPornLight
global.__objectDepths[376] = 1; // objPoliceDesk
global.__objectDepths[377] = 1; // objPoliceDeskPuter
global.__objectDepths[378] = 1; // objInterrogationTable
global.__objectDepths[379] = 1; // objSpeakerBooth
global.__objectDepths[380] = 1; // objPoliceArmchair
global.__objectDepths[381] = 2; // objPoliceDeskChair
global.__objectDepths[382] = -11; // objMetalDetector
global.__objectDepths[383] = 1; // objPaperbin
global.__objectDepths[384] = 1; // objPoliceSofa
global.__objectDepths[385] = -2; // objFiles
global.__objectDepths[386] = 0; // objFileCabinet
global.__objectDepths[387] = 0; // objPoliceFrontDesk
global.__objectDepths[388] = 0; // objPoliceEntryDesk
global.__objectDepths[389] = 0; // objBigPoliceTable
global.__objectDepths[390] = 0; // objEvidenceTable
global.__objectDepths[391] = -5; // objSurveillanceCamera
global.__objectDepths[392] = 0; // objCellBed
global.__objectDepths[393] = 0; // objCellSink
global.__objectDepths[394] = 1; // objCellToilet
global.__objectDepths[395] = 0; // objCellDoor
global.__objectDepths[396] = 0; // objSurveillanceCenter
global.__objectDepths[397] = 0; // objBarricade1
global.__objectDepths[398] = 2; // objBarricade2
global.__objectDepths[399] = 0; // objCopCar
global.__objectDepths[400] = 0; // objPhoneRecorder
global.__objectDepths[401] = 1; // objPhoneTable
global.__objectDepths[402] = 0; // objPhone1
global.__objectDepths[403] = 0; // objPhone2
global.__objectDepths[404] = 0; // objTowels
global.__objectDepths[405] = 10; // objWaterPuddle
global.__objectDepths[406] = 0; // objBubbleBath
global.__objectDepths[407] = 0; // objGymLocker
global.__objectDepths[408] = 1; // objSaunaBench
global.__objectDepths[409] = 0; // objSunChair
global.__objectDepths[410] = 0; // objSolarium
global.__objectDepths[411] = 0; // objSolariumOpen
global.__objectDepths[412] = 0; // objHeater
global.__objectDepths[413] = 1; // objGymBench
global.__objectDepths[414] = -4; // objSaunaSteam
global.__objectDepths[415] = 0; // objCandleTable
global.__objectDepths[416] = 0; // objCandleTableBurning
global.__objectDepths[417] = 0; // objMassageTable
global.__objectDepths[418] = 0; // objEnormousFountain
global.__objectDepths[419] = 0; // objSaunaCurtain
global.__objectDepths[420] = 0; // objSaunaCounter
global.__objectDepths[421] = 0; // objSaunaFountain
global.__objectDepths[422] = 10; // objYinYang
global.__objectDepths[423] = 0; // objCeoTable
global.__objectDepths[424] = 0; // objReceptionDesk
global.__objectDepths[425] = 0; // objPhoneHom
global.__objectDepths[426] = 0; // objCeoDead
global.__objectDepths[427] = 0; // objEmployeeDead
global.__objectDepths[428] = 0; // objEmployeeDeadPiece
global.__objectDepths[429] = 0; // objEmployeeDeadWall
global.__objectDepths[430] = 0; // objWorkerdDead
global.__objectDepths[431] = 1; // objGolfBag
global.__objectDepths[432] = -1; // objWorker
global.__objectDepths[433] = -1; // objEmployee
global.__objectDepths[434] = -1; // objCEO
global.__objectDepths[435] = 0; // objPhoneHomSafe
global.__objectDepths[436] = 2; // objPhoneHomPainting
global.__objectDepths[437] = 0; // objPhoneHomPaintingWall
global.__objectDepths[438] = 0; // objGolfCourt
global.__objectDepths[439] = 0; // objNiklasFridge
global.__objectDepths[440] = 0; // objFreezer
global.__objectDepths[441] = 0; // objStoreShelf
global.__objectDepths[442] = 0; // objStoreFridge
global.__objectDepths[443] = 0; // objRegister
global.__objectDepths[444] = 0; // objDoubleFridge
global.__objectDepths[445] = -2; // objNeonSign
global.__objectDepths[446] = 0; // objFan
global.__objectDepths[447] = 0; // objStorePapers
global.__objectDepths[448] = 0; // objPizzaRegister
global.__objectDepths[449] = -1; // objPizzaOven
global.__objectDepths[450] = 0; // objPizzaDisplay
global.__objectDepths[451] = -1; // objPizzaCounter
global.__objectDepths[452] = 0; // objPizzaTable
global.__objectDepths[453] = 3; // sprVHSDoorMat
global.__objectDepths[454] = 0; // objVHSRackH
global.__objectDepths[455] = 0; // objVHSRackV
global.__objectDepths[456] = 3; // objVHSTape
global.__objectDepths[457] = 0; // objVHSCounter
global.__objectDepths[458] = 0; // objVHSArchive
global.__objectDepths[459] = 0; // objBarPlant
global.__objectDepths[460] = 1; // objBarBooth
global.__objectDepths[461] = 1; // objBarStool
global.__objectDepths[462] = 0; // objBarRegister
global.__objectDepths[463] = 0; // objBarShelf
global.__objectDepths[464] = 0; // objJukebox
global.__objectDepths[465] = 0; // objBarTable
global.__objectDepths[466] = 0; // objBarPoolTable
global.__objectDepths[467] = 0; // objPhoneBooth
global.__objectDepths[468] = 1; // objHospitalChair
global.__objectDepths[469] = 0; // objHospitalBed
global.__objectDepths[470] = 0; // objHospitalBedStand
global.__objectDepths[471] = 1; // objHospitalCouch
global.__objectDepths[472] = 1; // objHospitalCouch2
global.__objectDepths[473] = 0; // objWheelChair
global.__objectDepths[474] = 0; // objHospitalDesk
global.__objectDepths[475] = 0; // objHospitalCupboard
global.__objectDepths[476] = 0; // objHospitalCurtains
global.__objectDepths[477] = 0; // objHospitalLocker
global.__objectDepths[478] = 0; // objHospitalSofaV
global.__objectDepths[479] = 0; // objHospitalSofaH
global.__objectDepths[480] = 3; // objHospitalElevator
global.__objectDepths[481] = -4; // objWindowOpen
global.__objectDepths[482] = -1; // objDoctorPatrol
global.__objectDepths[483] = -1; // objPoliceRead
global.__objectDepths[484] = 1; // objKeycard
global.__objectDepths[485] = 0; // objLockedDoor
global.__objectDepths[486] = 0; // objHandicapToilet
global.__objectDepths[487] = 0; // objHospitalReception
global.__objectDepths[488] = 0; // objGargoyle
global.__objectDepths[489] = 0; // objXray
global.__objectDepths[490] = 0; // objExamTable
global.__objectDepths[491] = 1; // objHospitalStaffSofa
global.__objectDepths[492] = 0; // objHospitalStaffMicro
global.__objectDepths[493] = 0; // objHospitalStaffTable
global.__objectDepths[494] = 1; // objRestaurantChair
global.__objectDepths[495] = 0; // objWineBottle
global.__objectDepths[496] = 0; // objBuffe
global.__objectDepths[497] = 0; // objFoodTray
global.__objectDepths[498] = 0; // objBuffePlates
global.__objectDepths[499] = 1; // objHotelSuiteSofa
global.__objectDepths[500] = 1; // objHotelSuiteChair
global.__objectDepths[501] = 0; // objHotelSuiteEntertainment
global.__objectDepths[502] = 0; // objHotelSimpleBed
global.__objectDepths[503] = 0; // objRestaurantTable
global.__objectDepths[504] = 0; // objHotelNightStandLight
global.__objectDepths[505] = 0; // objHotelNightStand
global.__objectDepths[506] = 0; // objHotelSuiteBed
global.__objectDepths[507] = 0; // objMinibar
global.__objectDepths[508] = 0; // objCleaningCart
global.__objectDepths[509] = 0; // objHotelCloset
global.__objectDepths[510] = 0; // objFootstand
global.__objectDepths[511] = 1; // objHotelChair
global.__objectDepths[512] = 3; // objWetSpot
global.__objectDepths[513] = 0; // objWetFloorWarning
global.__objectDepths[514] = 3; // objPoolTray
global.__objectDepths[515] = 0; // objPool
global.__objectDepths[516] = 0; // objPoolChair
global.__objectDepths[517] = 0; // objFireAxe
global.__objectDepths[518] = 1; // objKaraokeCouchPink
global.__objectDepths[519] = 1; // objKaraokeCouchBlack
global.__objectDepths[520] = 0; // objSpeakerTable
global.__objectDepths[521] = 0; // objKaraokeMachine
global.__objectDepths[522] = 0; // objHighballBooth
global.__objectDepths[523] = 0; // objLaneStart
global.__objectDepths[524] = 3; // objBowlingLane
global.__objectDepths[525] = 0; // objBowlingEnd
global.__objectDepths[526] = 0; // objLaptopTable
global.__objectDepths[527] = 0; // objHighballBoothBlack
global.__objectDepths[528] = 1; // objHighballChair
global.__objectDepths[529] = 0; // objSquareTable
global.__objectDepths[530] = -10; // objHighballCurtain
global.__objectDepths[531] = 1; // objHighballDiningChair
global.__objectDepths[532] = 1; // objHighballSign
global.__objectDepths[533] = 0; // objHighballBar
global.__objectDepths[534] = 0; // objVenuspatrol
global.__objectDepths[535] = 0; // objVenuspetrol
global.__objectDepths[536] = 0; // objVenuspatrolChalk
global.__objectDepths[537] = 0; // objBrandon
global.__objectDepths[538] = 0; // objSacrifice
global.__objectDepths[539] = 0; // objVenusPatrolSmall
global.__objectDepths[540] = 0; // objVenusCandle
global.__objectDepths[541] = 0; // objStroller
global.__objectDepths[542] = 0; // objEuroLogo
global.__objectDepths[543] = 0; // objBallOfDuty
global.__objectDepths[544] = 0; // objAssassinsBreed
global.__objectDepths[545] = 0; // object707
global.__objectDepths[546] = 0; // objRezzed
global.__objectDepths[547] = 0; // objHotlineLogo
global.__objectDepths[548] = 0; // objEuroPodV
global.__objectDepths[549] = 0; // objEuroPodH
global.__objectDepths[550] = 1; // objEuroFenceH
global.__objectDepths[551] = 1; // objEuroFenceV
global.__objectDepths[552] = 0; // objEuroPillar
global.__objectDepths[553] = 0; // objEuroIce
global.__objectDepths[554] = 0; // objEuroTrash
global.__objectDepths[555] = 1; // objPimpToilet
global.__objectDepths[556] = 0; // objBlackTub
global.__objectDepths[557] = 0; // objPimpSink
global.__objectDepths[558] = 0; // objMCKitchenShelf
global.__objectDepths[559] = 0; // objMCKitchenSink
global.__objectDepths[560] = 0; // objMCBed
global.__objectDepths[561] = 0; // objMCComputer
global.__objectDepths[562] = 1; // objMCCouch
global.__objectDepths[563] = 0; // objMCStereo
global.__objectDepths[564] = 0; // objMCGlassTable
global.__objectDepths[565] = 2; // objMCKeytar
global.__objectDepths[566] = 1; // objMCSkateboard
global.__objectDepths[567] = 0; // objMCStatue
global.__objectDepths[568] = 0; // objMCStove
global.__objectDepths[569] = 0; // objMCRecords
global.__objectDepths[570] = 0; // objUnderwear
global.__objectDepths[571] = 0; // objShoes
global.__objectDepths[572] = 0; // objMCTVTable
global.__objectDepths[573] = 0; // objMCTigerCarpet
global.__objectDepths[574] = 0; // objMCAquarium
global.__objectDepths[575] = 0; // objPimpPhone
global.__objectDepths[576] = 0; // objMCBottle
global.__objectDepths[577] = 0; // objProjector
global.__objectDepths[578] = -6; // objProjectorLight
global.__objectDepths[579] = 0; // objCopyMachine
global.__objectDepths[580] = 0; // objFileCabinetOffice
global.__objectDepths[581] = 0; // objConferenceTable
global.__objectDepths[582] = 1; // objOfficeCouch
global.__objectDepths[583] = 0; // objOfficeDesk
global.__objectDepths[584] = 1; // objOfficeCouchSmall
global.__objectDepths[585] = 0; // objProjectorTable
global.__objectDepths[586] = -2; // objVan
global.__objectDepths[587] = 0; // objGlassPanelDestroyedH
global.__objectDepths[588] = 0; // objGlassPanelDestroyedV
global.__objectDepths[589] = 0; // objOfficeDoor
global.__objectDepths[590] = 1; // objVanBottom
global.__objectDepths[591] = -5; // objExplosion
global.__objectDepths[592] = 2; // objBombCables
global.__objectDepths[593] = 0; // objDestroyedDoor
global.__objectDepths[594] = 0; // objDoorDebris
global.__objectDepths[595] = 0; // objWindowExplode
global.__objectDepths[596] = 0; // objTableBarricade
global.__objectDepths[597] = 0; // objDennisCouch
global.__objectDepths[598] = 0; // objAndersBed
global.__objectDepths[599] = 0; // objAndersCouch
global.__objectDepths[600] = 0; // objAndersDesk
global.__objectDepths[601] = 0; // objAndersTable
global.__objectDepths[602] = 0; // objLitterBox
global.__objectDepths[603] = 0; // objDennisBed
global.__objectDepths[604] = -1; // objDennisShelves
global.__objectDepths[605] = 0; // objDennisTable
global.__objectDepths[606] = 0; // objPeterCloset
global.__objectDepths[607] = 0; // objPetersBed
global.__objectDepths[608] = 0; // objPetersCouch
global.__objectDepths[609] = 0; // objPetersTub
global.__objectDepths[610] = 0; // objDennisTVBench
global.__objectDepths[611] = 3; // objEnvelopes
global.__objectDepths[612] = 0; // objDennisLivingRoomTable
global.__objectDepths[613] = 3; // objFloorMail
global.__objectDepths[614] = 0; // objAndersDrawer
global.__objectDepths[615] = -2; // objHatRack
global.__objectDepths[616] = 0; // objMailBoxes
global.__objectDepths[617] = 4; // objDanceFloor
global.__objectDepths[618] = -100; // objDiscoLights
global.__objectDepths[619] = 0; // objDiscoLight
global.__objectDepths[620] = 0; // objSpotlight
global.__objectDepths[621] = 0; // objDiscoBar
global.__objectDepths[622] = 0; // objDJRecords
global.__objectDepths[623] = 0; // objDJTable
global.__objectDepths[624] = 0; // objRecordPlayer
global.__objectDepths[625] = 0; // objDiscoRoofLight
global.__objectDepths[626] = 0; // objOldman
global.__objectDepths[627] = 0; // objPicture
global.__objectDepths[628] = 0; // objOldEntertainment
global.__objectDepths[629] = 0; // objOldFountain
global.__objectDepths[630] = 0; // objOldCouch
global.__objectDepths[631] = 0; // objOldBed
global.__objectDepths[632] = 0; // objOldNightstand
global.__objectDepths[633] = 0; // objOldPhone
global.__objectDepths[634] = 1; // objBossgun
global.__objectDepths[635] = -2; // objBossCar1
global.__objectDepths[636] = -2; // objBossCar2
global.__objectDepths[637] = -2; // objCarLift
global.__objectDepths[638] = -2; // objTyre
global.__objectDepths[639] = -2; // objToolTable
global.__objectDepths[640] = -2; // objWorkTable
global.__objectDepths[641] = 0; // objBoss4Pool
global.__objectDepths[642] = 7; // objGlassFloor
global.__objectDepths[643] = 7; // objGlassCross
global.__objectDepths[644] = 0; // objTrophyCabinet1
global.__objectDepths[645] = 0; // objTrophyCabinet2
global.__objectDepths[646] = 0; // objBoss4Sofa
global.__objectDepths[647] = -3; // objCyanPlant
global.__objectDepths[648] = 5; // objGlimmer
global.__objectDepths[649] = 0; // objArcadeCabinet
global.__objectDepths[650] = 0; // objHockeyTable
global.__objectDepths[651] = 0; // objBasketBallGame
global.__objectDepths[652] = -10; // objArcadeLight1
global.__objectDepths[653] = -10; // objArcadeLight2
global.__objectDepths[654] = 0; // objCarcade
global.__objectDepths[655] = 0; // objClawMachine
global.__objectDepths[656] = 0; // objFryingKitchen
global.__objectDepths[657] = 0; // objWokKitchen
global.__objectDepths[658] = 0; // objNoodleTable
global.__objectDepths[659] = 0; // objGoldenCat
global.__objectDepths[660] = 0; // objBuddha
global.__objectDepths[661] = 0; // objChineseFishtank
global.__objectDepths[662] = -3; // objBannerV
global.__objectDepths[663] = 0; // objGoldenDragon
global.__objectDepths[664] = 0; // objChineseLight
global.__objectDepths[665] = 0; // objChineseLightBlue
global.__objectDepths[666] = 0; // objGoldenBarBooth
global.__objectDepths[667] = 0; // objGoldenBar
global.__objectDepths[668] = 0; // objTruck
global.__objectDepths[669] = 0; // objTruckFence
global.__objectDepths[670] = 0; // objModernArt
global.__objectDepths[671] = 0; // objFancyBar
global.__objectDepths[672] = 1; // objWhiteBarStool
global.__objectDepths[673] = 0; // objStage
global.__objectDepths[674] = 0; // objStatueFence
global.__objectDepths[675] = 0; // objSmallTable
global.__objectDepths[676] = 0; // objClubSafe
global.__objectDepths[677] = 0; // objOwnerDesk
global.__objectDepths[678] = 3; // objClubSafePapers
global.__objectDepths[679] = -1; // objClubKeys
global.__objectDepths[680] = 0; // objClubRegister
global.__objectDepths[681] = 0; // objPantherStatue
global.__objectDepths[682] = 0; // objFloorTable
global.__objectDepths[683] = 0; // objSitCushion
global.__objectDepths[684] = 0; // objJapaneseTable
global.__objectDepths[685] = 0; // objJapaneseLiquor
global.__objectDepths[686] = 0; // objDrugTable
global.__objectDepths[687] = 0; // objCocaineBox
global.__objectDepths[688] = 0; // objCocaineCrate
global.__objectDepths[689] = -1; // objLaser
global.__objectDepths[690] = 0; // objBrokenWindowH
global.__objectDepths[691] = -1; // objSwat
global.__objectDepths[692] = 0; // objSwatOpenDoor
global.__objectDepths[693] = 0; // objSwatSpawn
global.__objectDepths[694] = 0; // objSwatVan
global.__objectDepths[695] = -10; // objSwatFade
global.__objectDepths[696] = 1; // objSwatKnockedOut
global.__objectDepths[697] = 0; // objDrugMaterial
global.__objectDepths[698] = 3; // objDrugSafe
global.__objectDepths[699] = 0; // objDrugCabinet
global.__objectDepths[700] = 0; // objShittyBar
global.__objectDepths[701] = 0; // objShittyBarShelf
global.__objectDepths[702] = 0; // objShittyBarTable
global.__objectDepths[703] = 1; // objLadder
global.__objectDepths[704] = 1001; // objSewerWaterLarge
global.__objectDepths[705] = 1001; // objSewerWaterSmall
global.__objectDepths[706] = 1001; // objSewerWaterMedium
global.__objectDepths[707] = 0; // objSewerPlans
global.__objectDepths[708] = 0; // objSewerTapes
global.__objectDepths[709] = 0; // objSewerForms
global.__objectDepths[710] = 0; // objSewerMasks
global.__objectDepths[711] = 0; // objSewerPhones
global.__objectDepths[712] = 0; // objWater
global.__objectDepths[713] = 0; // objJanitorPhoneBox
global.__objectDepths[714] = 0; // objJanitorBucket
global.__objectDepths[715] = 1; // objManhole
global.__objectDepths[716] = 0; // objManholeEquipment
global.__objectDepths[717] = 0; // objJanitorTable
global.__objectDepths[718] = 0; // objJanitorWorkBench
global.__objectDepths[719] = -4; // objManholePipe
global.__objectDepths[720] = 0; // objJanitorComputer
global.__objectDepths[721] = 1001; // objSewerFall1
global.__objectDepths[722] = 1001; // objSewerFall2
global.__objectDepths[723] = -12; // objSewerShadow
global.__objectDepths[724] = 0; // objCable1
global.__objectDepths[725] = 0; // objCable2
global.__objectDepths[726] = 0; // objTag
global.__objectDepths[727] = 0; // objBigTag
global.__objectDepths[728] = 1; // objSecretSewer
global.__objectDepths[729] = 1; // objSewerGrate
global.__objectDepths[730] = -12; // objSecretSewerShadow
global.__objectDepths[731] = 0; // objBossJacket
global.__objectDepths[732] = 0; // objBoss1Spawn
global.__objectDepths[733] = -1; // objBoss1
global.__objectDepths[734] = 1; // objBoss1Down
global.__objectDepths[735] = 0; // objBoss1Die
global.__objectDepths[736] = 1; // objBossChair
global.__objectDepths[737] = -1; // objBoss2
global.__objectDepths[738] = 0; // objCleaver
global.__objectDepths[739] = 0; // objBoss2Pry
global.__objectDepths[740] = 0; // objBoss2GetUp
global.__objectDepths[741] = 0; // objBoss2Crawl
global.__objectDepths[742] = 0; // objPBashBoss2
global.__objectDepths[743] = 1; // objBottleExplosion
global.__objectDepths[744] = -3; // objMolotov
global.__objectDepths[745] = 0; // objBurningGuy
global.__objectDepths[746] = 0; // objBoss3
global.__objectDepths[747] = 1; // objBoss3Kneel
global.__objectDepths[748] = 1; // _objBoss3Kneel
global.__objectDepths[749] = 1; // objBoss3Dead
global.__objectDepths[750] = 1; // objDeadBurning
global.__objectDepths[751] = 0; // objPlayerLighter
global.__objectDepths[752] = -1; // objBoss4
global.__objectDepths[753] = 1; // objBoss4Chair
global.__objectDepths[754] = 0; // objBoss4Desk
global.__objectDepths[755] = 0; // objBossFountain
global.__objectDepths[756] = 0; // objBodyguard
global.__objectDepths[757] = 2; // objPanther
global.__objectDepths[758] = 1; // objPantherBite
global.__objectDepths[759] = -1; // objBossPhone
global.__objectDepths[760] = 0; // objBodyguardCrawl
global.__objectDepths[761] = 0; // objBodyguardKnife
global.__objectDepths[762] = -1; // objPlayerBoss
global.__objectDepths[763] = -1; // objNicklasStore
global.__objectDepths[764] = -1; // objNicklasPizza
global.__objectDepths[765] = -1; // objNicklasVHS
global.__objectDepths[766] = -1; // objNicklasBar
global.__objectDepths[767] = -1; // objNicklasStoreSpecial
global.__objectDepths[768] = 2; // objNickeDead
global.__objectDepths[769] = 2; // objNickeTiedUp
global.__objectDepths[770] = -1; // objPrisoner
global.__objectDepths[771] = 1; // objAssassinGround
global.__objectDepths[772] = 1; // objAssassinDie
global.__objectDepths[773] = -1; // objAssassinPizza
global.__objectDepths[774] = -1; // objAssassinWait
global.__objectDepths[775] = -1; // objAssassinSitUzi
global.__objectDepths[776] = -1; // objAssassinVHS
global.__objectDepths[777] = -1; // objAssassinBar
global.__objectDepths[778] = -1; // objDreamPeople
global.__objectDepths[779] = -1; // objDreamPlayer
global.__objectDepths[780] = 2; // objGirlfriendDead
global.__objectDepths[781] = 2; // objGirlfriendDeadOutline
global.__objectDepths[782] = -1; // objGirlfriend
global.__objectDepths[783] = -1; // objGirlfriendBathroom
global.__objectDepths[784] = -1; // objGirlfriendSit
global.__objectDepths[785] = -1; // objDoctorTalk
global.__objectDepths[786] = -1; // objPoliceTalk
global.__objectDepths[787] = -1; // objHobo
global.__objectDepths[788] = 1; // objHoboKnockedOut
global.__objectDepths[789] = -1; // objDeadTable
global.__objectDepths[790] = -1; // objWileyWiggins
global.__objectDepths[791] = -1; // objDogPetCorpse
global.__objectDepths[792] = -1; // objFatCorpseEat
global.__objectDepths[793] = -1; // objCrocodileMan
global.__objectDepths[794] = -1; // objJanitorVacuum
global.__objectDepths[795] = -1; // objJanitorClean
global.__objectDepths[796] = -1; // objJanitorNotice
global.__objectDepths[797] = -1; // objJanitorFlee
global.__objectDepths[798] = -1; // objJanitor
global.__objectDepths[799] = 1; // objJanitorDennisDie
global.__objectDepths[800] = 1; // objJanitorJonatanDie
global.__objectDepths[801] = -1; // objETauntChain
global.__objectDepths[802] = -1; // objETauntPipe
global.__objectDepths[803] = -1; // objETauntBat
global.__objectDepths[804] = -1; // objVictimWall
global.__objectDepths[805] = -1; // objETauntSmoke
global.__objectDepths[806] = 0; // objEBombTinker
global.__objectDepths[807] = 0; // objEStandGuardBomb
global.__objectDepths[808] = 0; // objBombGuy
global.__objectDepths[809] = 0; // objBombGuyDie
global.__objectDepths[810] = 2; // objCobraDead
global.__objectDepths[811] = 2; // objLocustDead
global.__objectDepths[812] = 0; // objWalrusDead
global.__objectDepths[813] = -1; // objSunAraw
global.__objectDepths[814] = -1; // objCoconuts
global.__objectDepths[815] = -1; // objPerturbator
global.__objectDepths[816] = -1; // objJasper
global.__objectDepths[817] = 2; // objMoon
global.__objectDepths[818] = -1; // objElliott
global.__objectDepths[819] = -1; // objScattle
global.__objectDepths[820] = -1; // objEirik
global.__objectDepths[821] = -1; // objGirlfriendEat
global.__objectDepths[822] = -1; // objMCDate
global.__objectDepths[823] = -1; // objLoneSurvivor
global.__objectDepths[824] = 2; // objBoss2Corpse
global.__objectDepths[825] = -1; // objDJ
global.__objectDepths[826] = -10; // objTutorialHobo
global.__objectDepths[827] = -2; // objOscar
global.__objectDepths[828] = -2; // objBenjamin
global.__objectDepths[829] = 0; // objOscarTable
global.__objectDepths[830] = -1; // objOscarPlate
global.__objectDepths[831] = -1; // objNigelScream
global.__objectDepths[832] = -1; // objRasmus
global.__objectDepths[833] = -1; // objRasmusHat
global.__objectDepths[834] = 0; // objDevolver
global.__objectDepths[835] = 0; // objSplash


global.__objectNames[0] = "objPlayerMouse";
global.__objectNames[1] = "objPlayerMouseHouse";
global.__objectNames[2] = "objPlayerShieldMouse";
global.__objectNames[3] = "objMaskMenu";
global.__objectNames[4] = "objPlayerCarEnter";
global.__objectNames[5] = "objPlayerHospital";
global.__objectNames[6] = "objMaskDrop";
global.__objectNames[7] = "objPlayerDead";
global.__objectNames[8] = "objPlayerBombDead";
global.__objectNames[9] = "objPlayerOpenWindow";
global.__objectNames[10] = "objPWalkWindow";
global.__objectNames[11] = "objPlayerEnterWindow";
global.__objectNames[12] = "objPVomit";
global.__objectNames[13] = "objVomit";
global.__objectNames[14] = "objPlayerTurning";
global.__objectNames[15] = "objPlayerRipTape";
global.__objectNames[16] = "objPoliceTape";
global.__objectNames[17] = "objPoliceTapeRipped";
global.__objectNames[18] = "objClubOwner";
global.__objectNames[19] = "objPKillOwner";
global.__objectNames[20] = "objPlayerOpenGrate";
global.__objectNames[21] = "objPlayerClimbDown";
global.__objectNames[22] = "objPlayerClimbUp";
global.__objectNames[23] = "objEnemyBash";
global.__objectNames[24] = "objPAttackThroat";
global.__objectNames[25] = "objEnemyHeadKick";
global.__objectNames[26] = "objPBrickKill";
global.__objectNames[27] = "objPAttackSnap";
global.__objectNames[28] = "objPBluntKill";
global.__objectNames[29] = "objPAxeKill";
global.__objectNames[30] = "objPScissorKill";
global.__objectNames[31] = "objPSwordKill";
global.__objectNames[32] = "objPKnifeKill";
global.__objectNames[33] = "objPPoolKill";
global.__objectNames[34] = "objPBrokenPoolKill";
global.__objectNames[35] = "objPClubBoss2";
global.__objectNames[36] = "objPHoboBash";
global.__objectNames[37] = "objPHoboBlunt";
global.__objectNames[38] = "objPBodyguardBlunt";
global.__objectNames[39] = "objPBodyguardBash";
global.__objectNames[40] = "objPDrillKill";
global.__objectNames[41] = "objPSledgeKill";
global.__objectNames[42] = "objPMacheteKill";
global.__objectNames[43] = "objPBottleKill";
global.__objectNames[44] = "objPDartKill";
global.__objectNames[45] = "objPBoilingPotKill";
global.__objectNames[46] = "objPKillBodyguard";
global.__objectNames[47] = "objPHammerKill";
global.__objectNames[48] = "objPlayerBiker";
global.__objectNames[49] = "objPlayerBikerHouse";
global.__objectNames[50] = "objMCBike";
global.__objectNames[51] = "objMCHelmet";
global.__objectNames[52] = "objThrowingKnife";
global.__objectNames[53] = "objMCBartender";
global.__objectNames[54] = "objBartender";
global.__objectNames[55] = "objBikerSushi";
global.__objectNames[56] = "objSushiGuy";
global.__objectNames[57] = "objPlayerKneel";
global.__objectNames[58] = "objPlayerBikerKick";
global.__objectNames[59] = "objBikerClimbDown";
global.__objectNames[60] = "objBikerClimbUp";
global.__objectNames[61] = "objBikeEnding";
global.__objectNames[62] = "objPalmTreeTop";
global.__objectNames[63] = "objBikerKillJonatan";
global.__objectNames[64] = "objPlayerBikerHack";
global.__objectNames[65] = "objMCStompKill";
global.__objectNames[66] = "objMCChopKill";
global.__objectNames[67] = "objMCKnifeKill";
global.__objectNames[68] = "objPigButcher";
global.__objectNames[69] = "objPigButcherHeadbutt";
global.__objectNames[70] = "objPigButcherKill";
global.__objectNames[71] = "objEffector";
global.__objectNames[72] = "objEffectorHouse";
global.__objectNames[73] = "objEffectorHospital";
global.__objectNames[74] = "objEffectorInstant";
global.__objectNames[75] = "objSurfacer";
global.__objectNames[76] = "objBackgroundColor";
global.__objectNames[77] = "objBackgroundColorClear";
global.__objectNames[78] = "objPlayer";
global.__objectNames[79] = "objDoorV";
global.__objectNames[80] = "objDoorH";
global.__objectNames[81] = "objDoorV2";
global.__objectNames[82] = "objDoorH2";
global.__objectNames[83] = "objHospitalEntranceDoors";
global.__objectNames[84] = "objWallHeavyV";
global.__objectNames[85] = "objWallHeavyH";
global.__objectNames[86] = "objWallSoftV";
global.__objectNames[87] = "objWallSoftH";
global.__objectNames[88] = "objSewerWallV";
global.__objectNames[89] = "objSewerWallH";
global.__objectNames[90] = "objCellWallV";
global.__objectNames[91] = "objCellWallH";
global.__objectNames[92] = "objWallBrickV";
global.__objectNames[93] = "objWallBrickH";
global.__objectNames[94] = "objWallHospitalV";
global.__objectNames[95] = "objWallHospitalH";
global.__objectNames[96] = "objGlassPanelV";
global.__objectNames[97] = "objGlassPanelVBroken";
global.__objectNames[98] = "objGlassPanelH";
global.__objectNames[99] = "objGlassPanelHBroken";
global.__objectNames[100] = "objWindowV";
global.__objectNames[101] = "objWindowH";
global.__objectNames[102] = "objRailV";
global.__objectNames[103] = "objRailH";
global.__objectNames[104] = "objWoodFenceV";
global.__objectNames[105] = "objWoodFenceH";
global.__objectNames[106] = "objBalconyV";
global.__objectNames[107] = "objBalconyH";
global.__objectNames[108] = "objHorBarrier";
global.__objectNames[109] = "objVertBarrier";
global.__objectNames[110] = "objSolid";
global.__objectNames[111] = "objCorner";
global.__objectNames[112] = "objTransitioner";
global.__objectNames[113] = "objElevator";
global.__objectNames[114] = "objPolice";
global.__objectNames[115] = "objPolicePatrol";
global.__objectNames[116] = "objPoliceStationary";
global.__objectNames[117] = "objPoliceMelee";
global.__objectNames[118] = "objPoliceMeleeStationary";
global.__objectNames[119] = "objInspector";
global.__objectNames[120] = "objChief";
global.__objectNames[121] = "objPoliceHat";
global.__objectNames[122] = "objFatmanEating";
global.__objectNames[123] = "objFatmanTelephone";
global.__objectNames[124] = "objFatmanShit";
global.__objectNames[125] = "objWaiter";
global.__objectNames[126] = "objWaiterStationary";
global.__objectNames[127] = "objEnemyIdlePee";
global.__objectNames[128] = "objEnemyIdleSmoke";
global.__objectNames[129] = "objEnemySit";
global.__objectNames[130] = "objEnemyIdleGuard";
global.__objectNames[131] = "objEnemySitDrink";
global.__objectNames[132] = "objEnemyDrink";
global.__objectNames[133] = "objEnemyPhone";
global.__objectNames[134] = "objCellPhone";
global.__objectNames[135] = "objEnemyIdle";
global.__objectNames[136] = "objEnemy";
global.__objectNames[137] = "objEnemyPatrol";
global.__objectNames[138] = "objEnemyStationary";
global.__objectNames[139] = "objEnemyMelee";
global.__objectNames[140] = "objEnemyMeleeStationary";
global.__objectNames[141] = "objEHideM16";
global.__objectNames[142] = "objDogPatrol";
global.__objectNames[143] = "objEnemyFat";
global.__objectNames[144] = "objKnockedOut";
global.__objectNames[145] = "objDeadBody";
global.__objectNames[146] = "objBodyPart";
global.__objectNames[147] = "objECrawl";
global.__objectNames[148] = "objDogBite";
global.__objectNames[149] = "objESubwayStatic";
global.__objectNames[150] = "objSubwayKnockedOut";
global.__objectNames[151] = "objEGiveUp";
global.__objectNames[152] = "objBox";
global.__objectNames[153] = "objOpenedBox";
global.__objectNames[154] = "objDumpster";
global.__objectNames[155] = "objInvestigationFileSpread";
global.__objectNames[156] = "objPlayerForm";
global.__objectNames[157] = "objMCForm";
global.__objectNames[158] = "objBedClip";
global.__objectNames[159] = "objKitchenShelfClip";
global.__objectNames[160] = "objLivingRoomClip1";
global.__objectNames[161] = "objLivingRoomClip2";
global.__objectNames[162] = "objTableClip";
global.__objectNames[163] = "objKitchenCounterClip1";
global.__objectNames[164] = "objKitchenCounterClip3";
global.__objectNames[165] = "objKitchenCounterClip2";
global.__objectNames[166] = "objBriefcase";
global.__objectNames[167] = "objVHSTake";
global.__objectNames[168] = "objPizzaTake";
global.__objectNames[169] = "objDrink";
global.__objectNames[170] = "objSixpack";
global.__objectNames[171] = "objChipsBag";
global.__objectNames[172] = "objKeys";
global.__objectNames[173] = "objPlayerJacket";
global.__objectNames[174] = "objPlayerPants";
global.__objectNames[175] = "objToken";
global.__objectNames[176] = "objSecretMask";
global.__objectNames[177] = "objWeapon";
global.__objectNames[178] = "objSpecificWeapon";
global.__objectNames[179] = "objWeaponThrow";
global.__objectNames[180] = "objThrowingWeapon";
global.__objectNames[181] = "objBullet";
global.__objectNames[182] = "objEBullet";
global.__objectNames[183] = "objBulletHit";
global.__objectNames[184] = "objBloodDrop2";
global.__objectNames[185] = "objBloodCut";
global.__objectNames[186] = "objBloodHit";
global.__objectNames[187] = "objBloodSmoke2";
global.__objectNames[188] = "objBloodSplat2";
global.__objectNames[189] = "objBrains2";
global.__objectNames[190] = "objBrainChunk2";
global.__objectNames[191] = "objGuts2";
global.__objectNames[192] = "objSkinPiece2";
global.__objectNames[193] = "objBloodSmoke";
global.__objectNames[194] = "objBloodSplat";
global.__objectNames[195] = "objBloodDrop";
global.__objectNames[196] = "objBloodPool";
global.__objectNames[197] = "objBloodSquirt";
global.__objectNames[198] = "objBrains";
global.__objectNames[199] = "objHit";
global.__objectNames[200] = "objSmokeHit";
global.__objectNames[201] = "objShell";
global.__objectNames[202] = "objDebris";
global.__objectNames[203] = "objShard";
global.__objectNames[204] = "objTinyShard";
global.__objectNames[205] = "objFlies";
global.__objectNames[206] = "objSteam";
global.__objectNames[207] = "objPWater";
global.__objectNames[208] = "objSpark2";
global.__objectNames[209] = "objSpark1";
global.__objectNames[210] = "objBombGround";
global.__objectNames[211] = "objFloatingBottle";
global.__objectNames[212] = "objClip";
global.__objectNames[213] = "objDriveSmoke";
global.__objectNames[214] = "objBrokenBottle";
global.__objectNames[215] = "objTitle";
global.__objectNames[216] = "objPalmTree";
global.__objectNames[217] = "objHouse";
global.__objectNames[218] = "objLevelSelect";
global.__objectNames[219] = "objShowControls";
global.__objectNames[220] = "objPause";
global.__objectNames[221] = "objScore";
global.__objectNames[222] = "objLevelComplete";
global.__objectNames[223] = "objMaskUnlock";
global.__objectNames[224] = "objWeaponUnlock";
global.__objectNames[225] = "objLevelTitle";
global.__objectNames[226] = "objMCLevelTitle";
global.__objectNames[227] = "objHospitalTitle";
global.__objectNames[228] = "objPartTitle";
global.__objectNames[229] = "objInterlude";
global.__objectNames[230] = "objBandCredits";
global.__objectNames[231] = "objWave";
global.__objectNames[232] = "objCredits";
global.__objectNames[233] = "objSpread";
global.__objectNames[234] = "objLightingEngine";
global.__objectNames[235] = "objLight";
global.__objectNames[236] = "objLightingNormal";
global.__objectNames[237] = "objLightNormal";
global.__objectNames[238] = "objLetterSocket";
global.__objectNames[239] = "objLetter";
global.__objectNames[240] = "objPuzzle";
global.__objectNames[241] = "objLetterDone";
global.__objectNames[242] = "objLetterFound";
global.__objectNames[243] = "objScanlines";
global.__objectNames[244] = "objShadowH";
global.__objectNames[245] = "objShadowV";
global.__objectNames[246] = "objShootThrough";
global.__objectNames[247] = "objFurniture";
global.__objectNames[248] = "objPhoneConversation";
global.__objectNames[249] = "objSurfaceReturn";
global.__objectNames[250] = "objTeleporter";
global.__objectNames[251] = "objScoreStats";
global.__objectNames[252] = "objBoss";
global.__objectNames[253] = "objHouseReturn";
global.__objectNames[254] = "objCheckpoint";
global.__objectNames[255] = "objExporter";
global.__objectNames[256] = "objTrainshake";
global.__objectNames[257] = "objElectricLight";
global.__objectNames[258] = "objHospitalTransition";
global.__objectNames[259] = "objHospitalTalk";
global.__objectNames[260] = "objDizzy";
global.__objectNames[261] = "objEmpty";
global.__objectNames[262] = "objMiscEnemy";
global.__objectNames[263] = "objFlameParticle";
global.__objectNames[264] = "objBoss3Spawn";
global.__objectNames[265] = "objSequence12Light";
global.__objectNames[266] = "objTutorialLight";
global.__objectNames[267] = "objGoToCar";
global.__objectNames[268] = "objScoreDetails";
global.__objectNames[269] = "objSunSparkle";
global.__objectNames[270] = "objDateRewind";
global.__objectNames[271] = "objFinalDialogue";
global.__objectNames[272] = "objFinalDialogue2";
global.__objectNames[273] = "objAlienWare";
global.__objectNames[274] = "objSteamQuestion";
global.__objectNames[275] = "objFocus";
global.__objectNames[276] = "objTub";
global.__objectNames[277] = "objSink";
global.__objectNames[278] = "objUrinalV";
global.__objectNames[279] = "objToilet";
global.__objectNames[280] = "objShowerCurtain";
global.__objectNames[281] = "objJacuzzi";
global.__objectNames[282] = "objShowerGlassV";
global.__objectNames[283] = "objShowerGlassH";
global.__objectNames[284] = "objShowerGlassDoor";
global.__objectNames[285] = "objHotelSuiteTub";
global.__objectNames[286] = "objHotelSink";
global.__objectNames[287] = "objHotelSuiteToilet";
global.__objectNames[288] = "objChair";
global.__objectNames[289] = "objShelves";
global.__objectNames[290] = "objKitchenSink";
global.__objectNames[291] = "objStove";
global.__objectNames[292] = "objTable";
global.__objectNames[293] = "objMicrowave";
global.__objectNames[294] = "objFridge";
global.__objectNames[295] = "objToyBall";
global.__objectNames[296] = "objToyTurtle";
global.__objectNames[297] = "objToyBear";
global.__objectNames[298] = "objToyLego";
global.__objectNames[299] = "objToyM16";
global.__objectNames[300] = "objToyMP5";
global.__objectNames[301] = "objPelletsCorner";
global.__objectNames[302] = "objPelletsSide";
global.__objectNames[303] = "objPellets";
global.__objectNames[304] = "objPelletPlant";
global.__objectNames[305] = "objPlant";
global.__objectNames[306] = "objHospitalPlant";
global.__objectNames[307] = "objPizza";
global.__objectNames[308] = "objTrashbag";
global.__objectNames[309] = "objTrashcan";
global.__objectNames[310] = "objBurningTrashcan";
global.__objectNames[311] = "objHomelessBed";
global.__objectNames[312] = "objSofaV64";
global.__objectNames[313] = "objSofaV48";
global.__objectNames[314] = "objSofaH64";
global.__objectNames[315] = "objDrawerV24";
global.__objectNames[316] = "objDrawerH24";
global.__objectNames[317] = "objSofaH48";
global.__objectNames[318] = "objShirts";
global.__objectNames[319] = "objCassetteDeck";
global.__objectNames[320] = "objComputer";
global.__objectNames[321] = "objVinylRecord";
global.__objectNames[322] = "objBigTable";
global.__objectNames[323] = "objBeds";
global.__objectNames[324] = "objLamps";
global.__objectNames[325] = "objJackets";
global.__objectNames[326] = "objNes";
global.__objectNames[327] = "objVinylPlayer";
global.__objectNames[328] = "objSpeaker";
global.__objectNames[329] = "objTVBlack";
global.__objectNames[330] = "objTigerCarpet";
global.__objectNames[331] = "objFountain";
global.__objectNames[332] = "objBigBed";
global.__objectNames[333] = "objLeatherCouch";
global.__objectNames[334] = "objPoolTable";
global.__objectNames[335] = "objGlassTable";
global.__objectNames[336] = "objNightStand";
global.__objectNames[337] = "objTrophyHead";
global.__objectNames[338] = "objWineRack";
global.__objectNames[339] = "objCouchCushion";
global.__objectNames[340] = "objArmchair";
global.__objectNames[341] = "objRichTable";
global.__objectNames[342] = "objDiningChair";
global.__objectNames[343] = "objLaundryBasket";
global.__objectNames[344] = "objCarBottom";
global.__objectNames[345] = "objAquarium";
global.__objectNames[346] = "objAquariumBreak";
global.__objectNames[347] = "objAquariumWater";
global.__objectNames[348] = "objPhone";
global.__objectNames[349] = "objVendingMachine";
global.__objectNames[350] = "objTVWallMounted";
global.__objectNames[351] = "objLockerH";
global.__objectNames[352] = "objLockerV";
global.__objectNames[353] = "objSubwayBenchV";
global.__objectNames[354] = "objSubwayBench";
global.__objectNames[355] = "objTrain";
global.__objectNames[356] = "objSubwayDoor";
global.__objectNames[357] = "objClotheslineH";
global.__objectNames[358] = "objClotheslineV";
global.__objectNames[359] = "objAnsweringMachine";
global.__objectNames[360] = "objPlayerBed1";
global.__objectNames[361] = "objPlayerBed2";
global.__objectNames[362] = "objPlayerCouch";
global.__objectNames[363] = "objPlayerKitchenCounter";
global.__objectNames[364] = "objPlayerKitchenShelf";
global.__objectNames[365] = "objPlayerKitchenSink";
global.__objectNames[366] = "objPlayerLivingRoomTable";
global.__objectNames[367] = "objPlayerFridge";
global.__objectNames[368] = "objPlayerTable";
global.__objectNames[369] = "objVomitBucket";
global.__objectNames[370] = "objPlayerTub";
global.__objectNames[371] = "objGate";
global.__objectNames[372] = "objMonitors";
global.__objectNames[373] = "objPornBed";
global.__objectNames[374] = "objPornCamera";
global.__objectNames[375] = "objPornLight";
global.__objectNames[376] = "objPoliceDesk";
global.__objectNames[377] = "objPoliceDeskPuter";
global.__objectNames[378] = "objInterrogationTable";
global.__objectNames[379] = "objSpeakerBooth";
global.__objectNames[380] = "objPoliceArmchair";
global.__objectNames[381] = "objPoliceDeskChair";
global.__objectNames[382] = "objMetalDetector";
global.__objectNames[383] = "objPaperbin";
global.__objectNames[384] = "objPoliceSofa";
global.__objectNames[385] = "objFiles";
global.__objectNames[386] = "objFileCabinet";
global.__objectNames[387] = "objPoliceFrontDesk";
global.__objectNames[388] = "objPoliceEntryDesk";
global.__objectNames[389] = "objBigPoliceTable";
global.__objectNames[390] = "objEvidenceTable";
global.__objectNames[391] = "objSurveillanceCamera";
global.__objectNames[392] = "objCellBed";
global.__objectNames[393] = "objCellSink";
global.__objectNames[394] = "objCellToilet";
global.__objectNames[395] = "objCellDoor";
global.__objectNames[396] = "objSurveillanceCenter";
global.__objectNames[397] = "objBarricade1";
global.__objectNames[398] = "objBarricade2";
global.__objectNames[399] = "objCopCar";
global.__objectNames[400] = "objPhoneRecorder";
global.__objectNames[401] = "objPhoneTable";
global.__objectNames[402] = "objPhone1";
global.__objectNames[403] = "objPhone2";
global.__objectNames[404] = "objTowels";
global.__objectNames[405] = "objWaterPuddle";
global.__objectNames[406] = "objBubbleBath";
global.__objectNames[407] = "objGymLocker";
global.__objectNames[408] = "objSaunaBench";
global.__objectNames[409] = "objSunChair";
global.__objectNames[410] = "objSolarium";
global.__objectNames[411] = "objSolariumOpen";
global.__objectNames[412] = "objHeater";
global.__objectNames[413] = "objGymBench";
global.__objectNames[414] = "objSaunaSteam";
global.__objectNames[415] = "objCandleTable";
global.__objectNames[416] = "objCandleTableBurning";
global.__objectNames[417] = "objMassageTable";
global.__objectNames[418] = "objEnormousFountain";
global.__objectNames[419] = "objSaunaCurtain";
global.__objectNames[420] = "objSaunaCounter";
global.__objectNames[421] = "objSaunaFountain";
global.__objectNames[422] = "objYinYang";
global.__objectNames[423] = "objCeoTable";
global.__objectNames[424] = "objReceptionDesk";
global.__objectNames[425] = "objPhoneHom";
global.__objectNames[426] = "objCeoDead";
global.__objectNames[427] = "objEmployeeDead";
global.__objectNames[428] = "objEmployeeDeadPiece";
global.__objectNames[429] = "objEmployeeDeadWall";
global.__objectNames[430] = "objWorkerdDead";
global.__objectNames[431] = "objGolfBag";
global.__objectNames[432] = "objWorker";
global.__objectNames[433] = "objEmployee";
global.__objectNames[434] = "objCEO";
global.__objectNames[435] = "objPhoneHomSafe";
global.__objectNames[436] = "objPhoneHomPainting";
global.__objectNames[437] = "objPhoneHomPaintingWall";
global.__objectNames[438] = "objGolfCourt";
global.__objectNames[439] = "objNiklasFridge";
global.__objectNames[440] = "objFreezer";
global.__objectNames[441] = "objStoreShelf";
global.__objectNames[442] = "objStoreFridge";
global.__objectNames[443] = "objRegister";
global.__objectNames[444] = "objDoubleFridge";
global.__objectNames[445] = "objNeonSign";
global.__objectNames[446] = "objFan";
global.__objectNames[447] = "objStorePapers";
global.__objectNames[448] = "objPizzaRegister";
global.__objectNames[449] = "objPizzaOven";
global.__objectNames[450] = "objPizzaDisplay";
global.__objectNames[451] = "objPizzaCounter";
global.__objectNames[452] = "objPizzaTable";
global.__objectNames[453] = "sprVHSDoorMat";
global.__objectNames[454] = "objVHSRackH";
global.__objectNames[455] = "objVHSRackV";
global.__objectNames[456] = "objVHSTape";
global.__objectNames[457] = "objVHSCounter";
global.__objectNames[458] = "objVHSArchive";
global.__objectNames[459] = "objBarPlant";
global.__objectNames[460] = "objBarBooth";
global.__objectNames[461] = "objBarStool";
global.__objectNames[462] = "objBarRegister";
global.__objectNames[463] = "objBarShelf";
global.__objectNames[464] = "objJukebox";
global.__objectNames[465] = "objBarTable";
global.__objectNames[466] = "objBarPoolTable";
global.__objectNames[467] = "objPhoneBooth";
global.__objectNames[468] = "objHospitalChair";
global.__objectNames[469] = "objHospitalBed";
global.__objectNames[470] = "objHospitalBedStand";
global.__objectNames[471] = "objHospitalCouch";
global.__objectNames[472] = "objHospitalCouch2";
global.__objectNames[473] = "objWheelChair";
global.__objectNames[474] = "objHospitalDesk";
global.__objectNames[475] = "objHospitalCupboard";
global.__objectNames[476] = "objHospitalCurtains";
global.__objectNames[477] = "objHospitalLocker";
global.__objectNames[478] = "objHospitalSofaV";
global.__objectNames[479] = "objHospitalSofaH";
global.__objectNames[480] = "objHospitalElevator";
global.__objectNames[481] = "objWindowOpen";
global.__objectNames[482] = "objDoctorPatrol";
global.__objectNames[483] = "objPoliceRead";
global.__objectNames[484] = "objKeycard";
global.__objectNames[485] = "objLockedDoor";
global.__objectNames[486] = "objHandicapToilet";
global.__objectNames[487] = "objHospitalReception";
global.__objectNames[488] = "objGargoyle";
global.__objectNames[489] = "objXray";
global.__objectNames[490] = "objExamTable";
global.__objectNames[491] = "objHospitalStaffSofa";
global.__objectNames[492] = "objHospitalStaffMicro";
global.__objectNames[493] = "objHospitalStaffTable";
global.__objectNames[494] = "objRestaurantChair";
global.__objectNames[495] = "objWineBottle";
global.__objectNames[496] = "objBuffe";
global.__objectNames[497] = "objFoodTray";
global.__objectNames[498] = "objBuffePlates";
global.__objectNames[499] = "objHotelSuiteSofa";
global.__objectNames[500] = "objHotelSuiteChair";
global.__objectNames[501] = "objHotelSuiteEntertainment";
global.__objectNames[502] = "objHotelSimpleBed";
global.__objectNames[503] = "objRestaurantTable";
global.__objectNames[504] = "objHotelNightStandLight";
global.__objectNames[505] = "objHotelNightStand";
global.__objectNames[506] = "objHotelSuiteBed";
global.__objectNames[507] = "objMinibar";
global.__objectNames[508] = "objCleaningCart";
global.__objectNames[509] = "objHotelCloset";
global.__objectNames[510] = "objFootstand";
global.__objectNames[511] = "objHotelChair";
global.__objectNames[512] = "objWetSpot";
global.__objectNames[513] = "objWetFloorWarning";
global.__objectNames[514] = "objPoolTray";
global.__objectNames[515] = "objPool";
global.__objectNames[516] = "objPoolChair";
global.__objectNames[517] = "objFireAxe";
global.__objectNames[518] = "objKaraokeCouchPink";
global.__objectNames[519] = "objKaraokeCouchBlack";
global.__objectNames[520] = "objSpeakerTable";
global.__objectNames[521] = "objKaraokeMachine";
global.__objectNames[522] = "objHighballBooth";
global.__objectNames[523] = "objLaneStart";
global.__objectNames[524] = "objBowlingLane";
global.__objectNames[525] = "objBowlingEnd";
global.__objectNames[526] = "objLaptopTable";
global.__objectNames[527] = "objHighballBoothBlack";
global.__objectNames[528] = "objHighballChair";
global.__objectNames[529] = "objSquareTable";
global.__objectNames[530] = "objHighballCurtain";
global.__objectNames[531] = "objHighballDiningChair";
global.__objectNames[532] = "objHighballSign";
global.__objectNames[533] = "objHighballBar";
global.__objectNames[534] = "objVenuspatrol";
global.__objectNames[535] = "objVenuspetrol";
global.__objectNames[536] = "objVenuspatrolChalk";
global.__objectNames[537] = "objBrandon";
global.__objectNames[538] = "objSacrifice";
global.__objectNames[539] = "objVenusPatrolSmall";
global.__objectNames[540] = "objVenusCandle";
global.__objectNames[541] = "objStroller";
global.__objectNames[542] = "objEuroLogo";
global.__objectNames[543] = "objBallOfDuty";
global.__objectNames[544] = "objAssassinsBreed";
global.__objectNames[545] = "object707";
global.__objectNames[546] = "objRezzed";
global.__objectNames[547] = "objHotlineLogo";
global.__objectNames[548] = "objEuroPodV";
global.__objectNames[549] = "objEuroPodH";
global.__objectNames[550] = "objEuroFenceH";
global.__objectNames[551] = "objEuroFenceV";
global.__objectNames[552] = "objEuroPillar";
global.__objectNames[553] = "objEuroIce";
global.__objectNames[554] = "objEuroTrash";
global.__objectNames[555] = "objPimpToilet";
global.__objectNames[556] = "objBlackTub";
global.__objectNames[557] = "objPimpSink";
global.__objectNames[558] = "objMCKitchenShelf";
global.__objectNames[559] = "objMCKitchenSink";
global.__objectNames[560] = "objMCBed";
global.__objectNames[561] = "objMCComputer";
global.__objectNames[562] = "objMCCouch";
global.__objectNames[563] = "objMCStereo";
global.__objectNames[564] = "objMCGlassTable";
global.__objectNames[565] = "objMCKeytar";
global.__objectNames[566] = "objMCSkateboard";
global.__objectNames[567] = "objMCStatue";
global.__objectNames[568] = "objMCStove";
global.__objectNames[569] = "objMCRecords";
global.__objectNames[570] = "objUnderwear";
global.__objectNames[571] = "objShoes";
global.__objectNames[572] = "objMCTVTable";
global.__objectNames[573] = "objMCTigerCarpet";
global.__objectNames[574] = "objMCAquarium";
global.__objectNames[575] = "objPimpPhone";
global.__objectNames[576] = "objMCBottle";
global.__objectNames[577] = "objProjector";
global.__objectNames[578] = "objProjectorLight";
global.__objectNames[579] = "objCopyMachine";
global.__objectNames[580] = "objFileCabinetOffice";
global.__objectNames[581] = "objConferenceTable";
global.__objectNames[582] = "objOfficeCouch";
global.__objectNames[583] = "objOfficeDesk";
global.__objectNames[584] = "objOfficeCouchSmall";
global.__objectNames[585] = "objProjectorTable";
global.__objectNames[586] = "objVan";
global.__objectNames[587] = "objGlassPanelDestroyedH";
global.__objectNames[588] = "objGlassPanelDestroyedV";
global.__objectNames[589] = "objOfficeDoor";
global.__objectNames[590] = "objVanBottom";
global.__objectNames[591] = "objExplosion";
global.__objectNames[592] = "objBombCables";
global.__objectNames[593] = "objDestroyedDoor";
global.__objectNames[594] = "objDoorDebris";
global.__objectNames[595] = "objWindowExplode";
global.__objectNames[596] = "objTableBarricade";
global.__objectNames[597] = "objDennisCouch";
global.__objectNames[598] = "objAndersBed";
global.__objectNames[599] = "objAndersCouch";
global.__objectNames[600] = "objAndersDesk";
global.__objectNames[601] = "objAndersTable";
global.__objectNames[602] = "objLitterBox";
global.__objectNames[603] = "objDennisBed";
global.__objectNames[604] = "objDennisShelves";
global.__objectNames[605] = "objDennisTable";
global.__objectNames[606] = "objPeterCloset";
global.__objectNames[607] = "objPetersBed";
global.__objectNames[608] = "objPetersCouch";
global.__objectNames[609] = "objPetersTub";
global.__objectNames[610] = "objDennisTVBench";
global.__objectNames[611] = "objEnvelopes";
global.__objectNames[612] = "objDennisLivingRoomTable";
global.__objectNames[613] = "objFloorMail";
global.__objectNames[614] = "objAndersDrawer";
global.__objectNames[615] = "objHatRack";
global.__objectNames[616] = "objMailBoxes";
global.__objectNames[617] = "objDanceFloor";
global.__objectNames[618] = "objDiscoLights";
global.__objectNames[619] = "objDiscoLight";
global.__objectNames[620] = "objSpotlight";
global.__objectNames[621] = "objDiscoBar";
global.__objectNames[622] = "objDJRecords";
global.__objectNames[623] = "objDJTable";
global.__objectNames[624] = "objRecordPlayer";
global.__objectNames[625] = "objDiscoRoofLight";
global.__objectNames[626] = "objOldman";
global.__objectNames[627] = "objPicture";
global.__objectNames[628] = "objOldEntertainment";
global.__objectNames[629] = "objOldFountain";
global.__objectNames[630] = "objOldCouch";
global.__objectNames[631] = "objOldBed";
global.__objectNames[632] = "objOldNightstand";
global.__objectNames[633] = "objOldPhone";
global.__objectNames[634] = "objBossgun";
global.__objectNames[635] = "objBossCar1";
global.__objectNames[636] = "objBossCar2";
global.__objectNames[637] = "objCarLift";
global.__objectNames[638] = "objTyre";
global.__objectNames[639] = "objToolTable";
global.__objectNames[640] = "objWorkTable";
global.__objectNames[641] = "objBoss4Pool";
global.__objectNames[642] = "objGlassFloor";
global.__objectNames[643] = "objGlassCross";
global.__objectNames[644] = "objTrophyCabinet1";
global.__objectNames[645] = "objTrophyCabinet2";
global.__objectNames[646] = "objBoss4Sofa";
global.__objectNames[647] = "objCyanPlant";
global.__objectNames[648] = "objGlimmer";
global.__objectNames[649] = "objArcadeCabinet";
global.__objectNames[650] = "objHockeyTable";
global.__objectNames[651] = "objBasketBallGame";
global.__objectNames[652] = "objArcadeLight1";
global.__objectNames[653] = "objArcadeLight2";
global.__objectNames[654] = "objCarcade";
global.__objectNames[655] = "objClawMachine";
global.__objectNames[656] = "objFryingKitchen";
global.__objectNames[657] = "objWokKitchen";
global.__objectNames[658] = "objNoodleTable";
global.__objectNames[659] = "objGoldenCat";
global.__objectNames[660] = "objBuddha";
global.__objectNames[661] = "objChineseFishtank";
global.__objectNames[662] = "objBannerV";
global.__objectNames[663] = "objGoldenDragon";
global.__objectNames[664] = "objChineseLight";
global.__objectNames[665] = "objChineseLightBlue";
global.__objectNames[666] = "objGoldenBarBooth";
global.__objectNames[667] = "objGoldenBar";
global.__objectNames[668] = "objTruck";
global.__objectNames[669] = "objTruckFence";
global.__objectNames[670] = "objModernArt";
global.__objectNames[671] = "objFancyBar";
global.__objectNames[672] = "objWhiteBarStool";
global.__objectNames[673] = "objStage";
global.__objectNames[674] = "objStatueFence";
global.__objectNames[675] = "objSmallTable";
global.__objectNames[676] = "objClubSafe";
global.__objectNames[677] = "objOwnerDesk";
global.__objectNames[678] = "objClubSafePapers";
global.__objectNames[679] = "objClubKeys";
global.__objectNames[680] = "objClubRegister";
global.__objectNames[681] = "objPantherStatue";
global.__objectNames[682] = "objFloorTable";
global.__objectNames[683] = "objSitCushion";
global.__objectNames[684] = "objJapaneseTable";
global.__objectNames[685] = "objJapaneseLiquor";
global.__objectNames[686] = "objDrugTable";
global.__objectNames[687] = "objCocaineBox";
global.__objectNames[688] = "objCocaineCrate";
global.__objectNames[689] = "objLaser";
global.__objectNames[690] = "objBrokenWindowH";
global.__objectNames[691] = "objSwat";
global.__objectNames[692] = "objSwatOpenDoor";
global.__objectNames[693] = "objSwatSpawn";
global.__objectNames[694] = "objSwatVan";
global.__objectNames[695] = "objSwatFade";
global.__objectNames[696] = "objSwatKnockedOut";
global.__objectNames[697] = "objDrugMaterial";
global.__objectNames[698] = "objDrugSafe";
global.__objectNames[699] = "objDrugCabinet";
global.__objectNames[700] = "objShittyBar";
global.__objectNames[701] = "objShittyBarShelf";
global.__objectNames[702] = "objShittyBarTable";
global.__objectNames[703] = "objLadder";
global.__objectNames[704] = "objSewerWaterLarge";
global.__objectNames[705] = "objSewerWaterSmall";
global.__objectNames[706] = "objSewerWaterMedium";
global.__objectNames[707] = "objSewerPlans";
global.__objectNames[708] = "objSewerTapes";
global.__objectNames[709] = "objSewerForms";
global.__objectNames[710] = "objSewerMasks";
global.__objectNames[711] = "objSewerPhones";
global.__objectNames[712] = "objWater";
global.__objectNames[713] = "objJanitorPhoneBox";
global.__objectNames[714] = "objJanitorBucket";
global.__objectNames[715] = "objManhole";
global.__objectNames[716] = "objManholeEquipment";
global.__objectNames[717] = "objJanitorTable";
global.__objectNames[718] = "objJanitorWorkBench";
global.__objectNames[719] = "objManholePipe";
global.__objectNames[720] = "objJanitorComputer";
global.__objectNames[721] = "objSewerFall1";
global.__objectNames[722] = "objSewerFall2";
global.__objectNames[723] = "objSewerShadow";
global.__objectNames[724] = "objCable1";
global.__objectNames[725] = "objCable2";
global.__objectNames[726] = "objTag";
global.__objectNames[727] = "objBigTag";
global.__objectNames[728] = "objSecretSewer";
global.__objectNames[729] = "objSewerGrate";
global.__objectNames[730] = "objSecretSewerShadow";
global.__objectNames[731] = "objBossJacket";
global.__objectNames[732] = "objBoss1Spawn";
global.__objectNames[733] = "objBoss1";
global.__objectNames[734] = "objBoss1Down";
global.__objectNames[735] = "objBoss1Die";
global.__objectNames[736] = "objBossChair";
global.__objectNames[737] = "objBoss2";
global.__objectNames[738] = "objCleaver";
global.__objectNames[739] = "objBoss2Pry";
global.__objectNames[740] = "objBoss2GetUp";
global.__objectNames[741] = "objBoss2Crawl";
global.__objectNames[742] = "objPBashBoss2";
global.__objectNames[743] = "objBottleExplosion";
global.__objectNames[744] = "objMolotov";
global.__objectNames[745] = "objBurningGuy";
global.__objectNames[746] = "objBoss3";
global.__objectNames[747] = "objBoss3Kneel";
global.__objectNames[748] = "_objBoss3Kneel";
global.__objectNames[749] = "objBoss3Dead";
global.__objectNames[750] = "objDeadBurning";
global.__objectNames[751] = "objPlayerLighter";
global.__objectNames[752] = "objBoss4";
global.__objectNames[753] = "objBoss4Chair";
global.__objectNames[754] = "objBoss4Desk";
global.__objectNames[755] = "objBossFountain";
global.__objectNames[756] = "objBodyguard";
global.__objectNames[757] = "objPanther";
global.__objectNames[758] = "objPantherBite";
global.__objectNames[759] = "objBossPhone";
global.__objectNames[760] = "objBodyguardCrawl";
global.__objectNames[761] = "objBodyguardKnife";
global.__objectNames[762] = "objPlayerBoss";
global.__objectNames[763] = "objNicklasStore";
global.__objectNames[764] = "objNicklasPizza";
global.__objectNames[765] = "objNicklasVHS";
global.__objectNames[766] = "objNicklasBar";
global.__objectNames[767] = "objNicklasStoreSpecial";
global.__objectNames[768] = "objNickeDead";
global.__objectNames[769] = "objNickeTiedUp";
global.__objectNames[770] = "objPrisoner";
global.__objectNames[771] = "objAssassinGround";
global.__objectNames[772] = "objAssassinDie";
global.__objectNames[773] = "objAssassinPizza";
global.__objectNames[774] = "objAssassinWait";
global.__objectNames[775] = "objAssassinSitUzi";
global.__objectNames[776] = "objAssassinVHS";
global.__objectNames[777] = "objAssassinBar";
global.__objectNames[778] = "objDreamPeople";
global.__objectNames[779] = "objDreamPlayer";
global.__objectNames[780] = "objGirlfriendDead";
global.__objectNames[781] = "objGirlfriendDeadOutline";
global.__objectNames[782] = "objGirlfriend";
global.__objectNames[783] = "objGirlfriendBathroom";
global.__objectNames[784] = "objGirlfriendSit";
global.__objectNames[785] = "objDoctorTalk";
global.__objectNames[786] = "objPoliceTalk";
global.__objectNames[787] = "objHobo";
global.__objectNames[788] = "objHoboKnockedOut";
global.__objectNames[789] = "objDeadTable";
global.__objectNames[790] = "objWileyWiggins";
global.__objectNames[791] = "objDogPetCorpse";
global.__objectNames[792] = "objFatCorpseEat";
global.__objectNames[793] = "objCrocodileMan";
global.__objectNames[794] = "objJanitorVacuum";
global.__objectNames[795] = "objJanitorClean";
global.__objectNames[796] = "objJanitorNotice";
global.__objectNames[797] = "objJanitorFlee";
global.__objectNames[798] = "objJanitor";
global.__objectNames[799] = "objJanitorDennisDie";
global.__objectNames[800] = "objJanitorJonatanDie";
global.__objectNames[801] = "objETauntChain";
global.__objectNames[802] = "objETauntPipe";
global.__objectNames[803] = "objETauntBat";
global.__objectNames[804] = "objVictimWall";
global.__objectNames[805] = "objETauntSmoke";
global.__objectNames[806] = "objEBombTinker";
global.__objectNames[807] = "objEStandGuardBomb";
global.__objectNames[808] = "objBombGuy";
global.__objectNames[809] = "objBombGuyDie";
global.__objectNames[810] = "objCobraDead";
global.__objectNames[811] = "objLocustDead";
global.__objectNames[812] = "objWalrusDead";
global.__objectNames[813] = "objSunAraw";
global.__objectNames[814] = "objCoconuts";
global.__objectNames[815] = "objPerturbator";
global.__objectNames[816] = "objJasper";
global.__objectNames[817] = "objMoon";
global.__objectNames[818] = "objElliott";
global.__objectNames[819] = "objScattle";
global.__objectNames[820] = "objEirik";
global.__objectNames[821] = "objGirlfriendEat";
global.__objectNames[822] = "objMCDate";
global.__objectNames[823] = "objLoneSurvivor";
global.__objectNames[824] = "objBoss2Corpse";
global.__objectNames[825] = "objDJ";
global.__objectNames[826] = "objTutorialHobo";
global.__objectNames[827] = "objOscar";
global.__objectNames[828] = "objBenjamin";
global.__objectNames[829] = "objOscarTable";
global.__objectNames[830] = "objOscarPlate";
global.__objectNames[831] = "objNigelScream";
global.__objectNames[832] = "objRasmus";
global.__objectNames[833] = "objRasmusHat";
global.__objectNames[834] = "objDevolver";
global.__objectNames[835] = "objSplash";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for