if argument0=0 return "" 
if argument0=1 return "F-" 
if argument0=2 return "F" 
if argument0=3 return "F+" 
if argument0=4 return "D-" 
if argument0=5 return "D" 
if argument0=6 return "D+" 
if argument0=7 return "C-" 
if argument0=8 return "C" 
if argument0=9 return "C+" 
if argument0=10 return "B-" 
if argument0=11 return "B" 
if argument0=12 return "B+" 
if argument0=13 return "A-" 
if argument0=14 return "A" 
if argument0=15 return "A+" 

return ""
