function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -2; // objPlayerMouse
	global.__objectDepths[1] = -2; // objPlayerMouseHouse
	global.__objectDepths[2] = -2; // objPlayerShieldMouse
	global.__objectDepths[3] = 0; // objPlayerController
	global.__objectDepths[4] = 0; // objMaskMenu
	global.__objectDepths[5] = -3; // objPlayerCarEnter
	global.__objectDepths[6] = -1; // objPlayerHospital
	global.__objectDepths[7] = 1; // objMaskDrop
	global.__objectDepths[8] = 2; // objPlayerDead
	global.__objectDepths[9] = 0; // objPlayerBombDead
	global.__objectDepths[10] = 0; // objPlayerOpenWindow
	global.__objectDepths[11] = -1; // objPWalkWindow
	global.__objectDepths[12] = -1; // objPlayerEnterWindow
	global.__objectDepths[13] = 0; // objPVomit
	global.__objectDepths[14] = 0; // objVomit
	global.__objectDepths[15] = 0; // objPlayerTurning
	global.__objectDepths[16] = 0; // objPlayerRipTape
	global.__objectDepths[17] = 0; // objPoliceTape
	global.__objectDepths[18] = 0; // objPoliceTapeRipped
	global.__objectDepths[19] = 0; // objClubOwner
	global.__objectDepths[20] = 0; // objPKillOwner
	global.__objectDepths[21] = 0; // objPlayerOpenGrate
	global.__objectDepths[22] = 0; // objPlayerClimbDown
	global.__objectDepths[23] = 0; // objPlayerClimbUp
	global.__objectDepths[24] = 0; // objEnemyBash
	global.__objectDepths[25] = 0; // objPAttackThroat
	global.__objectDepths[26] = 0; // objEnemyHeadKick
	global.__objectDepths[27] = 0; // objPBrickKill
	global.__objectDepths[28] = 0; // objPAttackSnap
	global.__objectDepths[29] = 0; // objPBluntKill
	global.__objectDepths[30] = 0; // objPAxeKill
	global.__objectDepths[31] = 0; // objPScissorKill
	global.__objectDepths[32] = 0; // objPSwordKill
	global.__objectDepths[33] = 0; // objPKnifeKill
	global.__objectDepths[34] = 0; // objPPoolKill
	global.__objectDepths[35] = 0; // objPBrokenPoolKill
	global.__objectDepths[36] = 0; // objPClubBoss2
	global.__objectDepths[37] = 0; // objPHoboBash
	global.__objectDepths[38] = 0; // objPHoboBlunt
	global.__objectDepths[39] = 0; // objPBodyguardBlunt
	global.__objectDepths[40] = 0; // objPBodyguardBash
	global.__objectDepths[41] = 0; // objPDrillKill
	global.__objectDepths[42] = 0; // objPSledgeKill
	global.__objectDepths[43] = 0; // objPMacheteKill
	global.__objectDepths[44] = 0; // objPBottleKill
	global.__objectDepths[45] = 0; // objPDartKill
	global.__objectDepths[46] = 0; // objPBoilingPotKill
	global.__objectDepths[47] = 0; // objPKillBodyguard
	global.__objectDepths[48] = 0; // objPHammerKill
	global.__objectDepths[49] = -2; // objPlayerBiker
	global.__objectDepths[50] = -2; // objPlayerBikerHouse
	global.__objectDepths[51] = 0; // objMCBike
	global.__objectDepths[52] = 1; // objMCHelmet
	global.__objectDepths[53] = 0; // objThrowingKnife
	global.__objectDepths[54] = 0; // objMCBartender
	global.__objectDepths[55] = 0; // objBartender
	global.__objectDepths[56] = 0; // objBikerSushi
	global.__objectDepths[57] = 0; // objSushiGuy
	global.__objectDepths[58] = 0; // objPlayerKneel
	global.__objectDepths[59] = -1; // objPlayerBikerKick
	global.__objectDepths[60] = 0; // objBikerClimbDown
	global.__objectDepths[61] = 0; // objBikerClimbUp
	global.__objectDepths[62] = -1; // objBikeEnding
	global.__objectDepths[63] = 0; // objPalmTreeTop
	global.__objectDepths[64] = 0; // objBikerKillJonatan
	global.__objectDepths[65] = -1; // objPlayerBikerHack
	global.__objectDepths[66] = 0; // objMCStompKill
	global.__objectDepths[67] = 0; // objMCChopKill
	global.__objectDepths[68] = 0; // objMCKnifeKill
	global.__objectDepths[69] = -1; // objPigButcher
	global.__objectDepths[70] = 0; // objPigButcherHeadbutt
	global.__objectDepths[71] = 0; // objPigButcherKill
	global.__objectDepths[72] = -10000; // objEffector
	global.__objectDepths[73] = -10000; // objEffectorHouse
	global.__objectDepths[74] = -10000; // objEffectorHospital
	global.__objectDepths[75] = -10000; // objEffectorInstant
	global.__objectDepths[76] = 3; // objSurfacer
	global.__objectDepths[77] = 9999999; // objBackgroundColor
	global.__objectDepths[78] = 9999999; // objBackgroundColorClear
	global.__objectDepths[79] = -1; // objPlayer
	global.__objectDepths[80] = 0; // objDoorV
	global.__objectDepths[81] = 0; // objDoorH
	global.__objectDepths[82] = 0; // objDoorV2
	global.__objectDepths[83] = 0; // objDoorH2
	global.__objectDepths[84] = -3; // objHospitalEntranceDoors
	global.__objectDepths[85] = -10; // objWallHeavyV
	global.__objectDepths[86] = -10; // objWallHeavyH
	global.__objectDepths[87] = -10; // objWallSoftV
	global.__objectDepths[88] = -10; // objWallSoftH
	global.__objectDepths[89] = -10; // objSewerWallV
	global.__objectDepths[90] = -10; // objSewerWallH
	global.__objectDepths[91] = -10; // objCementWallV
	global.__objectDepths[92] = -10; // objCementWallH
	global.__objectDepths[93] = -10; // objCellWallV
	global.__objectDepths[94] = -10; // objCellWallH
	global.__objectDepths[95] = -10; // objWoodWallInteriorV
	global.__objectDepths[96] = -10; // objWoodWallInteriorH
	global.__objectDepths[97] = -10; // objSubwayWallV
	global.__objectDepths[98] = -10; // objSubwayWallH
	global.__objectDepths[99] = -10; // objPorchWallH
	global.__objectDepths[100] = -10; // objPorchWallV
	global.__objectDepths[101] = -10; // objWallBrickV
	global.__objectDepths[102] = -10; // objWallBrickH
	global.__objectDepths[103] = -10; // objWallHospitalV
	global.__objectDepths[104] = -10; // objWallHospitalH
	global.__objectDepths[105] = -10; // objWoodWallV
	global.__objectDepths[106] = -10; // objWoodWallH
	global.__objectDepths[107] = -10; // objBunkerWallH
	global.__objectDepths[108] = -10; // objBunkerWallV
	global.__objectDepths[109] = -10; // objFenceH
	global.__objectDepths[110] = -10; // objFenceBroken
	global.__objectDepths[111] = -10; // objFenceV
	global.__objectDepths[112] = 0; // objGlassPanelV
	global.__objectDepths[113] = 0; // objGlassPanelVBroken
	global.__objectDepths[114] = 0; // objGlassPanelH
	global.__objectDepths[115] = 0; // objGlassPanelHBroken
	global.__objectDepths[116] = 0; // objWindowV
	global.__objectDepths[117] = 0; // objWindowLargeV
	global.__objectDepths[118] = 0; // objWindowH
	global.__objectDepths[119] = 0; // objWindowLargeH
	global.__objectDepths[120] = -10; // objSubwayWindowV
	global.__objectDepths[121] = -10; // objSubwayWindowH
	global.__objectDepths[122] = 0; // objRailV
	global.__objectDepths[123] = 0; // objRailH
	global.__objectDepths[124] = 0; // objWoodFenceV
	global.__objectDepths[125] = 0; // objWoodFenceH
	global.__objectDepths[126] = 0; // objBalconyV
	global.__objectDepths[127] = 0; // objBalconyH
	global.__objectDepths[128] = -10; // objBoatRailingH
	global.__objectDepths[129] = -10; // objBoatRailingV
	global.__objectDepths[130] = 0; // objHorBarrier
	global.__objectDepths[131] = 0; // objVertBarrier
	global.__objectDepths[132] = 0; // objSolid
	global.__objectDepths[133] = -10; // objCorner
	global.__objectDepths[134] = 0; // objTransitioner
	global.__objectDepths[135] = 3; // objElevator
	global.__objectDepths[136] = -1; // objPolice
	global.__objectDepths[137] = -1; // objPolicePatrol
	global.__objectDepths[138] = -1; // objPoliceStationary
	global.__objectDepths[139] = -1; // objPoliceMelee
	global.__objectDepths[140] = -1; // objPoliceMeleeStationary
	global.__objectDepths[141] = -1; // objInspector
	global.__objectDepths[142] = 0; // objChief
	global.__objectDepths[143] = 1; // objPoliceHat
	global.__objectDepths[144] = -1; // objFatmanEating
	global.__objectDepths[145] = -1; // objFatmanTelephone
	global.__objectDepths[146] = 0; // objFatmanShit
	global.__objectDepths[147] = 0; // objWaiter
	global.__objectDepths[148] = 0; // objWaiterStationary
	global.__objectDepths[149] = 0; // objEnemyIdlePee
	global.__objectDepths[150] = 0; // objEnemyIdleSmoke
	global.__objectDepths[151] = 0; // objEnemySit
	global.__objectDepths[152] = 0; // objEnemyIdleGuard
	global.__objectDepths[153] = 0; // objEnemySitDrink
	global.__objectDepths[154] = 0; // objEnemyDrink
	global.__objectDepths[155] = 0; // objEnemyPhone
	global.__objectDepths[156] = 1; // objCellPhone
	global.__objectDepths[157] = 0; // objEnemyIdle
	global.__objectDepths[158] = -1; // objEnemy
	global.__objectDepths[159] = -1; // objEnemyPatrol
	global.__objectDepths[160] = -1; // objEnemyStationary
	global.__objectDepths[161] = -1; // objEnemyMelee
	global.__objectDepths[162] = -1; // objEnemyMeleeStationary
	global.__objectDepths[163] = 0; // objEHideM16
	global.__objectDepths[164] = -1; // objDogPatrol
	global.__objectDepths[165] = -1; // objEnemyFat
	global.__objectDepths[166] = -1; // objEnemyMobile
	global.__objectDepths[167] = 1; // objKnockedOut
	global.__objectDepths[168] = 2; // objDeadBody
	global.__objectDepths[169] = 2; // objBodyPart
	global.__objectDepths[170] = 0; // objECrawl
	global.__objectDepths[171] = 1; // objDogBite
	global.__objectDepths[172] = -1; // objEnemyOld
	global.__objectDepths[173] = -1; // objDogPatrolOld
	global.__objectDepths[174] = -1; // objEnemyStationaryOld
	global.__objectDepths[175] = -1; // objEnemyPatrolOld
	global.__objectDepths[176] = -1; // objEnemyMeleeOld
	global.__objectDepths[177] = -1; // objEnemyMobileOld
	global.__objectDepths[178] = -1; // objEnemyMeleeStationaryOld
	global.__objectDepths[179] = -1; // objESubwayStatic
	global.__objectDepths[180] = 1; // objSubwayKnockedOut
	global.__objectDepths[181] = 0; // objEGiveUp
	global.__objectDepths[182] = 1; // objBox
	global.__objectDepths[183] = 2; // objOpenedBox
	global.__objectDepths[184] = 0; // objDumpster
	global.__objectDepths[185] = 0; // objInvestigationFileSpread
	global.__objectDepths[186] = -1; // objPlayerForm
	global.__objectDepths[187] = -1; // objMCForm
	global.__objectDepths[188] = -1; // objBedClip
	global.__objectDepths[189] = -1; // objKitchenShelfClip
	global.__objectDepths[190] = -1; // objLivingRoomClip1
	global.__objectDepths[191] = -1; // objLivingRoomClip2
	global.__objectDepths[192] = -1; // objTableClip
	global.__objectDepths[193] = -1; // objKitchenCounterClip1
	global.__objectDepths[194] = -1; // objKitchenCounterClip3
	global.__objectDepths[195] = -1; // objKitchenCounterClip2
	global.__objectDepths[196] = 1; // objBriefcase
	global.__objectDepths[197] = -1; // objVHSTake
	global.__objectDepths[198] = -1; // objPizzaTake
	global.__objectDepths[199] = -1; // objDrink
	global.__objectDepths[200] = -1; // objSixpack
	global.__objectDepths[201] = -1; // objChipsBag
	global.__objectDepths[202] = -1; // objKeys
	global.__objectDepths[203] = 1; // objPlayerJacket
	global.__objectDepths[204] = 1; // objPlayerPants
	global.__objectDepths[205] = 0; // objToken
	global.__objectDepths[206] = 1; // objSecretMask
	global.__objectDepths[207] = 1; // objWeapon
	global.__objectDepths[208] = -1; // objSpecificWeapon
	global.__objectDepths[209] = 0; // objWeaponThrow
	global.__objectDepths[210] = -2; // objThrowingWeapon
	global.__objectDepths[211] = -2; // objBullet
	global.__objectDepths[212] = -2; // objEBullet
	global.__objectDepths[213] = 0; // objBulletHit
	global.__objectDepths[214] = 0; // objBloodDrop2
	global.__objectDepths[215] = 0; // objBloodCut
	global.__objectDepths[216] = 0; // objBloodHit
	global.__objectDepths[217] = 0; // objBloodSmoke2
	global.__objectDepths[218] = 1; // objBulleter
	global.__objectDepths[219] = 2; // objBloodSplat2
	global.__objectDepths[220] = 1; // objBrains2
	global.__objectDepths[221] = 1; // objBrainChunk2
	global.__objectDepths[222] = 1; // objGuts2
	global.__objectDepths[223] = 1; // objSkinPiece2
	global.__objectDepths[224] = 0; // objBloodSmoke
	global.__objectDepths[225] = 2; // objBloodSplat
	global.__objectDepths[226] = 0; // objBloodDrop
	global.__objectDepths[227] = 3; // objBloodPool
	global.__objectDepths[228] = 0; // objBloodSquirt
	global.__objectDepths[229] = 0; // objBrains
	global.__objectDepths[230] = -9; // objHit
	global.__objectDepths[231] = -9; // objSmokeHit
	global.__objectDepths[232] = 0; // objShell
	global.__objectDepths[233] = 0; // objDebris
	global.__objectDepths[234] = 0; // objShard
	global.__objectDepths[235] = 0; // objTinyShard
	global.__objectDepths[236] = 0; // objFlies
	global.__objectDepths[237] = -9; // objSteam
	global.__objectDepths[238] = 0; // objPWater
	global.__objectDepths[239] = -17; // objSpark2
	global.__objectDepths[240] = -1; // objSpark1
	global.__objectDepths[241] = 3; // objBombGround
	global.__objectDepths[242] = 0; // objFloatingBottle
	global.__objectDepths[243] = 0; // objClip
	global.__objectDepths[244] = 0; // objDriveSmoke
	global.__objectDepths[245] = 1; // objBrokenBottle
	global.__objectDepths[246] = 0; // objTitle
	global.__objectDepths[247] = 0; // objPalmTree
	global.__objectDepths[248] = 0; // objHouse
	global.__objectDepths[249] = 0; // objLevelSelect
	global.__objectDepths[250] = 0; // objShowControls
	global.__objectDepths[251] = 0; // objPause
	global.__objectDepths[252] = -101; // objScore
	global.__objectDepths[253] = -10001; // objLevelComplete
	global.__objectDepths[254] = 0; // objMaskUnlock
	global.__objectDepths[255] = 0; // objWeaponUnlock
	global.__objectDepths[256] = 0; // objLevelTitle
	global.__objectDepths[257] = 0; // objMCLevelTitle
	global.__objectDepths[258] = 0; // objHospitalTitle
	global.__objectDepths[259] = 0; // objPartTitle
	global.__objectDepths[260] = 0; // objInterlude
	global.__objectDepths[261] = 0; // objBandCredits
	global.__objectDepths[262] = 0; // objWave
	global.__objectDepths[263] = 0; // objCredits
	global.__objectDepths[264] = 0; // objSpread
	global.__objectDepths[265] = -100; // objLightingEngine
	global.__objectDepths[266] = 0; // objLight
	global.__objectDepths[267] = -100; // objLightingNormal
	global.__objectDepths[268] = 0; // objLightNormal
	global.__objectDepths[269] = -1; // objLetterSocket
	global.__objectDepths[270] = -2; // objLetter
	global.__objectDepths[271] = -10; // objPuzzle
	global.__objectDepths[272] = -3; // objLetterDone
	global.__objectDepths[273] = -10001; // objLetterFound
	global.__objectDepths[274] = 0; // sxms
	global.__objectDepths[275] = 10000; // objVCapture
	global.__objectDepths[276] = 0; // objPathTest
	global.__objectDepths[277] = 10; // objShadowH
	global.__objectDepths[278] = 10; // objShadowV
	global.__objectDepths[279] = 0; // objShootThrough
	global.__objectDepths[280] = 0; // objFurniture
	global.__objectDepths[281] = 0; // objPhoneConversation
	global.__objectDepths[282] = 2; // objSurfaceReturn
	global.__objectDepths[283] = 0; // objTeleporter
	global.__objectDepths[284] = 0; // objScoreStats
	global.__objectDepths[285] = 0; // objBoss
	global.__objectDepths[286] = 0; // objHouseReturn
	global.__objectDepths[287] = -10001; // objCheckpoint
	global.__objectDepths[288] = 0; // objExporter
	global.__objectDepths[289] = 0; // objTrainshake
	global.__objectDepths[290] = -1; // objElectricLight
	global.__objectDepths[291] = 0; // objHospitalTransition
	global.__objectDepths[292] = 0; // objHospitalTalk
	global.__objectDepths[293] = -100000; // objDizzy
	global.__objectDepths[294] = 0; // objEmpty
	global.__objectDepths[295] = 0; // objMiscEnemy
	global.__objectDepths[296] = 0; // objFlameParticle
	global.__objectDepths[297] = 0; // objBoss3Spawn
	global.__objectDepths[298] = -100; // objSequence12Light
	global.__objectDepths[299] = -100; // objTutorialLight
	global.__objectDepths[300] = 0; // objGoToCar
	global.__objectDepths[301] = 0; // objScoreDetails
	global.__objectDepths[302] = 0; // objSunSparkle
	global.__objectDepths[303] = 0; // objDateRewind
	global.__objectDepths[304] = -1000; // objFinalDialogue
	global.__objectDepths[305] = -1000; // objFinalDialogue2
	global.__objectDepths[306] = 0; // objAlienWare
	global.__objectDepths[307] = 0; // objSteamQuestion
	global.__objectDepths[308] = 0; // objFocus
	global.__objectDepths[309] = 0; // objTub
	global.__objectDepths[310] = 1; // objSink
	global.__objectDepths[311] = 0; // objUrinalV
	global.__objectDepths[312] = 1; // objToilet
	global.__objectDepths[313] = -10; // objShowerCurtain
	global.__objectDepths[314] = 0; // objJacuzzi
	global.__objectDepths[315] = 0; // objShowerGlassV
	global.__objectDepths[316] = 0; // objShowerGlassH
	global.__objectDepths[317] = 0; // objShowerGlassDoor
	global.__objectDepths[318] = 0; // objHotelSuiteTub
	global.__objectDepths[319] = 0; // objHotelSink
	global.__objectDepths[320] = 1; // objHotelSuiteToilet
	global.__objectDepths[321] = 1; // objChair
	global.__objectDepths[322] = 0; // objShelves
	global.__objectDepths[323] = 0; // objKitchenSink
	global.__objectDepths[324] = 0; // objStove
	global.__objectDepths[325] = 1; // objTable
	global.__objectDepths[326] = 0; // objMicrowave
	global.__objectDepths[327] = 0; // objFridge
	global.__objectDepths[328] = 0; // objToyBall
	global.__objectDepths[329] = 0; // objToyTurtle
	global.__objectDepths[330] = 0; // objToyBear
	global.__objectDepths[331] = 0; // objToyLego
	global.__objectDepths[332] = 2; // objToyM16
	global.__objectDepths[333] = 2; // objToyMP5
	global.__objectDepths[334] = 0; // objPelletsCorner
	global.__objectDepths[335] = 0; // objPelletsSide
	global.__objectDepths[336] = 0; // objPellets
	global.__objectDepths[337] = -3; // objPelletPlant
	global.__objectDepths[338] = -1; // objPlant
	global.__objectDepths[339] = -3; // objHospitalPlant
	global.__objectDepths[340] = 1; // objPizza
	global.__objectDepths[341] = 1; // objTrashbag
	global.__objectDepths[342] = 1; // objTrashcan
	global.__objectDepths[343] = 1; // objBurningTrashcan
	global.__objectDepths[344] = 0; // objHomelessBed
	global.__objectDepths[345] = 1; // objSofaV64
	global.__objectDepths[346] = 1; // objSofaV48
	global.__objectDepths[347] = 1; // objSofaH64
	global.__objectDepths[348] = 0; // objDrawerV24
	global.__objectDepths[349] = 0; // objDrawerH24
	global.__objectDepths[350] = 1; // objSofaH48
	global.__objectDepths[351] = 10; // objShirts
	global.__objectDepths[352] = -1; // objCassetteDeck
	global.__objectDepths[353] = -1; // objComputer
	global.__objectDepths[354] = 0; // objVinylRecord
	global.__objectDepths[355] = 0; // objBigTable
	global.__objectDepths[356] = 0; // objBeds
	global.__objectDepths[357] = -1; // objLamps
	global.__objectDepths[358] = 10; // objJackets
	global.__objectDepths[359] = 0; // objNes
	global.__objectDepths[360] = -1; // objVinylPlayer
	global.__objectDepths[361] = 0; // objSpeaker
	global.__objectDepths[362] = -1; // objTVBlack
	global.__objectDepths[363] = 10; // objTigerCarpet
	global.__objectDepths[364] = 0; // objFountain
	global.__objectDepths[365] = 0; // objBigBed
	global.__objectDepths[366] = 1; // objLeatherCouch
	global.__objectDepths[367] = 0; // objPoolTable
	global.__objectDepths[368] = 0; // objGlassTable
	global.__objectDepths[369] = 0; // objNightStand
	global.__objectDepths[370] = -4; // objTrophyHead
	global.__objectDepths[371] = 1; // objWineRack
	global.__objectDepths[372] = 0; // objCouchCushion
	global.__objectDepths[373] = 1; // objArmchair
	global.__objectDepths[374] = 0; // objRichTable
	global.__objectDepths[375] = 1; // objDiningChair
	global.__objectDepths[376] = 1; // objLaundryBasket
	global.__objectDepths[377] = 3; // objCarBottom
	global.__objectDepths[378] = 0; // objAquarium
	global.__objectDepths[379] = 1; // objAquariumBreak
	global.__objectDepths[380] = 3; // objAquariumWater
	global.__objectDepths[381] = -1; // objPhone
	global.__objectDepths[382] = -2; // objVendingMachine
	global.__objectDepths[383] = -4; // objTVWallMounted
	global.__objectDepths[384] = 0; // objLockerH
	global.__objectDepths[385] = 0; // objLockerV
	global.__objectDepths[386] = 1; // objSubwayBenchV
	global.__objectDepths[387] = 1; // objSubwayBench
	global.__objectDepths[388] = -3; // objTrain
	global.__objectDepths[389] = -4; // objSubwayDoor
	global.__objectDepths[390] = -4; // objClotheslineH
	global.__objectDepths[391] = -4; // objClotheslineV
	global.__objectDepths[392] = 0; // objAnsweringMachine
	global.__objectDepths[393] = 0; // objPlayerBed1
	global.__objectDepths[394] = 0; // objPlayerBed2
	global.__objectDepths[395] = 1; // objPlayerCouch
	global.__objectDepths[396] = 0; // objPlayerKitchenCounter
	global.__objectDepths[397] = 0; // objPlayerKitchenShelf
	global.__objectDepths[398] = 0; // objPlayerKitchenSink
	global.__objectDepths[399] = 0; // objPlayerLivingRoomTable
	global.__objectDepths[400] = 0; // objPlayerFridge
	global.__objectDepths[401] = 0; // objPlayerTable
	global.__objectDepths[402] = 1; // objVomitBucket
	global.__objectDepths[403] = 0; // objPlayerTub
	global.__objectDepths[404] = 0; // objGate
	global.__objectDepths[405] = 1; // objMonitors
	global.__objectDepths[406] = 1; // objPornBed
	global.__objectDepths[407] = 0; // objPornCamera
	global.__objectDepths[408] = -1; // objPornLight
	global.__objectDepths[409] = 1; // objPoliceDesk
	global.__objectDepths[410] = 1; // objPoliceDeskPuter
	global.__objectDepths[411] = 1; // objInterrogationTable
	global.__objectDepths[412] = 1; // objSpeakerBooth
	global.__objectDepths[413] = 1; // objPoliceArmchair
	global.__objectDepths[414] = 2; // objPoliceDeskChair
	global.__objectDepths[415] = -11; // objMetalDetector
	global.__objectDepths[416] = 1; // objPaperbin
	global.__objectDepths[417] = 1; // objPoliceSofa
	global.__objectDepths[418] = -2; // objFiles
	global.__objectDepths[419] = 0; // objFileCabinet
	global.__objectDepths[420] = 0; // objPoliceFrontDesk
	global.__objectDepths[421] = 0; // objPoliceEntryDesk
	global.__objectDepths[422] = 0; // objBigPoliceTable
	global.__objectDepths[423] = 0; // objEvidenceTable
	global.__objectDepths[424] = -5; // objSurveillanceCamera
	global.__objectDepths[425] = 0; // objCellBed
	global.__objectDepths[426] = 0; // objCellSink
	global.__objectDepths[427] = 1; // objCellToilet
	global.__objectDepths[428] = 0; // objCellDoor
	global.__objectDepths[429] = 0; // objSurveillanceCenter
	global.__objectDepths[430] = 0; // objBarricade1
	global.__objectDepths[431] = 2; // objBarricade2
	global.__objectDepths[432] = 0; // objCopCar
	global.__objectDepths[433] = 0; // objPhoneRecorder
	global.__objectDepths[434] = 1; // objPhoneTable
	global.__objectDepths[435] = 0; // objPhone1
	global.__objectDepths[436] = 0; // objPhone2
	global.__objectDepths[437] = 0; // objTowels
	global.__objectDepths[438] = 10; // objWaterPuddle
	global.__objectDepths[439] = 0; // objBubbleBath
	global.__objectDepths[440] = 0; // objGymLocker
	global.__objectDepths[441] = 1; // objSaunaBench
	global.__objectDepths[442] = 0; // objSunChair
	global.__objectDepths[443] = 0; // objSolarium
	global.__objectDepths[444] = 0; // objSolariumOpen
	global.__objectDepths[445] = 0; // objHeater
	global.__objectDepths[446] = 1; // objGymBench
	global.__objectDepths[447] = -4; // objSaunaSteam
	global.__objectDepths[448] = 0; // objCandleTable
	global.__objectDepths[449] = 0; // objCandleTableBurning
	global.__objectDepths[450] = 0; // objMassageTable
	global.__objectDepths[451] = 0; // objEnormousFountain
	global.__objectDepths[452] = 0; // objSaunaCurtain
	global.__objectDepths[453] = 0; // objSaunaCounter
	global.__objectDepths[454] = 0; // objSaunaFountain
	global.__objectDepths[455] = 10; // objYinYang
	global.__objectDepths[456] = 0; // objCeoTable
	global.__objectDepths[457] = 0; // objReceptionDesk
	global.__objectDepths[458] = 0; // objPhoneHom
	global.__objectDepths[459] = 0; // objCeoDead
	global.__objectDepths[460] = 0; // objEmployeeDead
	global.__objectDepths[461] = 0; // objEmployeeDeadPiece
	global.__objectDepths[462] = 0; // objEmployeeDeadWall
	global.__objectDepths[463] = 0; // objWorkerdDead
	global.__objectDepths[464] = 1; // objGolfBag
	global.__objectDepths[465] = -1; // objWorker
	global.__objectDepths[466] = -1; // objEmployee
	global.__objectDepths[467] = -1; // objCEO
	global.__objectDepths[468] = 0; // objPhoneHomSafe
	global.__objectDepths[469] = 2; // objPhoneHomPainting
	global.__objectDepths[470] = 0; // objPhoneHomPaintingWall
	global.__objectDepths[471] = 0; // objGolfCourt
	global.__objectDepths[472] = 0; // objNiklasFridge
	global.__objectDepths[473] = 0; // objFreezer
	global.__objectDepths[474] = 0; // objStoreShelf
	global.__objectDepths[475] = 0; // objStoreFridge
	global.__objectDepths[476] = 0; // objRegister
	global.__objectDepths[477] = 0; // objDoubleFridge
	global.__objectDepths[478] = -2; // objNeonSign
	global.__objectDepths[479] = 0; // objFan
	global.__objectDepths[480] = 0; // objStorePapers
	global.__objectDepths[481] = 0; // objPizzaRegister
	global.__objectDepths[482] = -1; // objPizzaOven
	global.__objectDepths[483] = 0; // objPizzaDisplay
	global.__objectDepths[484] = -1; // objPizzaCounter
	global.__objectDepths[485] = 0; // objPizzaTable
	global.__objectDepths[486] = 3; // sprVHSDoorMat
	global.__objectDepths[487] = 0; // objVHSRackH
	global.__objectDepths[488] = 0; // objVHSRackV
	global.__objectDepths[489] = 3; // objVHSTape
	global.__objectDepths[490] = 0; // objVHSCounter
	global.__objectDepths[491] = 0; // objVHSArchive
	global.__objectDepths[492] = 0; // objBarPlant
	global.__objectDepths[493] = 1; // objBarBooth
	global.__objectDepths[494] = 1; // objBarStool
	global.__objectDepths[495] = 0; // objBarRegister
	global.__objectDepths[496] = 0; // objBarShelf
	global.__objectDepths[497] = 0; // objJukebox
	global.__objectDepths[498] = 0; // objBarTable
	global.__objectDepths[499] = 0; // objBarPoolTable
	global.__objectDepths[500] = 0; // objPhoneBooth
	global.__objectDepths[501] = 1; // objHospitalChair
	global.__objectDepths[502] = 0; // objHospitalBed
	global.__objectDepths[503] = 0; // objHospitalBedStand
	global.__objectDepths[504] = 1; // objHospitalCouch
	global.__objectDepths[505] = 1; // objHospitalCouch2
	global.__objectDepths[506] = 0; // objWheelChair
	global.__objectDepths[507] = 0; // objHospitalDesk
	global.__objectDepths[508] = 0; // objHospitalCupboard
	global.__objectDepths[509] = 0; // objHospitalCurtains
	global.__objectDepths[510] = 0; // objHospitalLocker
	global.__objectDepths[511] = 0; // objHospitalSofaV
	global.__objectDepths[512] = 0; // objHospitalSofaH
	global.__objectDepths[513] = 3; // objHospitalElevator
	global.__objectDepths[514] = -4; // objWindowOpen
	global.__objectDepths[515] = -1; // objDoctorPatrol
	global.__objectDepths[516] = -1; // objPoliceRead
	global.__objectDepths[517] = 1; // objKeycard
	global.__objectDepths[518] = 0; // objLockedDoor
	global.__objectDepths[519] = 0; // objHandicapToilet
	global.__objectDepths[520] = 0; // objHospitalReception
	global.__objectDepths[521] = 0; // objGargoyle
	global.__objectDepths[522] = 0; // objXray
	global.__objectDepths[523] = 0; // objExamTable
	global.__objectDepths[524] = 1; // objHospitalStaffSofa
	global.__objectDepths[525] = 0; // objHospitalStaffMicro
	global.__objectDepths[526] = 0; // objHospitalStaffTable
	global.__objectDepths[527] = 1; // objRestaurantChair
	global.__objectDepths[528] = 0; // objWineBottle
	global.__objectDepths[529] = 0; // objBuffe
	global.__objectDepths[530] = 0; // objFoodTray
	global.__objectDepths[531] = 0; // objBuffePlates
	global.__objectDepths[532] = 1; // objHotelSuiteSofa
	global.__objectDepths[533] = 1; // objHotelSuiteChair
	global.__objectDepths[534] = 0; // objHotelSuiteEntertainment
	global.__objectDepths[535] = 0; // objHotelSimpleBed
	global.__objectDepths[536] = 0; // objRestaurantTable
	global.__objectDepths[537] = 0; // objHotelNightStandLight
	global.__objectDepths[538] = 0; // objHotelNightStand
	global.__objectDepths[539] = 0; // objHotelSuiteBed
	global.__objectDepths[540] = 0; // objMinibar
	global.__objectDepths[541] = 0; // objCleaningCart
	global.__objectDepths[542] = 0; // objHotelCloset
	global.__objectDepths[543] = 0; // objFootstand
	global.__objectDepths[544] = 1; // objHotelChair
	global.__objectDepths[545] = 3; // objWetSpot
	global.__objectDepths[546] = 0; // objWetFloorWarning
	global.__objectDepths[547] = 3; // objPoolTray
	global.__objectDepths[548] = 0; // objPool
	global.__objectDepths[549] = 0; // objPoolChair
	global.__objectDepths[550] = 0; // objFireAxe
	global.__objectDepths[551] = 1; // objKaraokeCouchPink
	global.__objectDepths[552] = 1; // objKaraokeCouchBlack
	global.__objectDepths[553] = 0; // objSpeakerTable
	global.__objectDepths[554] = 0; // objKaraokeMachine
	global.__objectDepths[555] = 0; // objHighballBooth
	global.__objectDepths[556] = 0; // objLaneStart
	global.__objectDepths[557] = 3; // objBowlingLane
	global.__objectDepths[558] = 0; // objBowlingEnd
	global.__objectDepths[559] = 0; // objLaptopTable
	global.__objectDepths[560] = 0; // objHighballBoothBlack
	global.__objectDepths[561] = 1; // objHighballChair
	global.__objectDepths[562] = 0; // objSquareTable
	global.__objectDepths[563] = -10; // objHighballCurtain
	global.__objectDepths[564] = 1; // objHighballDiningChair
	global.__objectDepths[565] = 1; // objHighballSign
	global.__objectDepths[566] = 0; // objHighballBar
	global.__objectDepths[567] = 0; // objVenuspatrol
	global.__objectDepths[568] = 0; // objVenuspetrol
	global.__objectDepths[569] = 0; // objVenuspatrolChalk
	global.__objectDepths[570] = 0; // objBrandon
	global.__objectDepths[571] = 0; // objSacrifice
	global.__objectDepths[572] = 0; // objVenusPatrolSmall
	global.__objectDepths[573] = 0; // objVenusCandle
	global.__objectDepths[574] = 0; // objStroller
	global.__objectDepths[575] = 0; // objEuroLogo
	global.__objectDepths[576] = 0; // objBallOfDuty
	global.__objectDepths[577] = 0; // objAssassinsBreed
	global.__objectDepths[578] = 0; // object707
	global.__objectDepths[579] = 0; // objRezzed
	global.__objectDepths[580] = 0; // objHotlineLogo
	global.__objectDepths[581] = 0; // objEuroPodV
	global.__objectDepths[582] = 0; // objEuroPodH
	global.__objectDepths[583] = 1; // objEuroFenceH
	global.__objectDepths[584] = 1; // objEuroFenceV
	global.__objectDepths[585] = 0; // objEuroPillar
	global.__objectDepths[586] = 0; // objEuroIce
	global.__objectDepths[587] = 0; // objEuroTrash
	global.__objectDepths[588] = 1; // objPimpToilet
	global.__objectDepths[589] = 0; // objBlackTub
	global.__objectDepths[590] = 0; // objPimpSink
	global.__objectDepths[591] = 0; // objMCKitchenShelf
	global.__objectDepths[592] = 0; // objMCKitchenSink
	global.__objectDepths[593] = 0; // objMCBed
	global.__objectDepths[594] = 0; // objMCComputer
	global.__objectDepths[595] = 1; // objMCCouch
	global.__objectDepths[596] = 0; // objMCStereo
	global.__objectDepths[597] = 0; // objMCGlassTable
	global.__objectDepths[598] = 2; // objMCKeytar
	global.__objectDepths[599] = 1; // objMCSkateboard
	global.__objectDepths[600] = 0; // objMCStatue
	global.__objectDepths[601] = 0; // objMCStove
	global.__objectDepths[602] = 0; // objMCRecords
	global.__objectDepths[603] = 0; // objUnderwear
	global.__objectDepths[604] = 0; // objShoes
	global.__objectDepths[605] = 0; // objMCTVTable
	global.__objectDepths[606] = 0; // objMCTigerCarpet
	global.__objectDepths[607] = 0; // objMCAquarium
	global.__objectDepths[608] = 0; // objPimpPhone
	global.__objectDepths[609] = 0; // objMCBottle
	global.__objectDepths[610] = 0; // objProjector
	global.__objectDepths[611] = -6; // objProjectorLight
	global.__objectDepths[612] = 0; // objCopyMachine
	global.__objectDepths[613] = 0; // objFileCabinetOffice
	global.__objectDepths[614] = 0; // objConferenceTable
	global.__objectDepths[615] = 1; // objOfficeCouch
	global.__objectDepths[616] = 0; // objOfficeDesk
	global.__objectDepths[617] = 1; // objOfficeCouchSmall
	global.__objectDepths[618] = 0; // objProjectorTable
	global.__objectDepths[619] = -2; // objVan
	global.__objectDepths[620] = 0; // objGlassPanelDestroyedH
	global.__objectDepths[621] = 0; // objGlassPanelDestroyedV
	global.__objectDepths[622] = 0; // objOfficeDoor
	global.__objectDepths[623] = 1; // objVanBottom
	global.__objectDepths[624] = -5; // objExplosion
	global.__objectDepths[625] = 2; // objBombCables
	global.__objectDepths[626] = 0; // objDestroyedDoor
	global.__objectDepths[627] = 0; // objDoorDebris
	global.__objectDepths[628] = 0; // objWindowExplode
	global.__objectDepths[629] = 0; // objTableBarricade
	global.__objectDepths[630] = 0; // objDennisCouch
	global.__objectDepths[631] = 0; // objAndersBed
	global.__objectDepths[632] = 0; // objAndersCouch
	global.__objectDepths[633] = 0; // objAndersDesk
	global.__objectDepths[634] = 0; // objAndersTable
	global.__objectDepths[635] = 0; // objLitterBox
	global.__objectDepths[636] = 0; // objDennisBed
	global.__objectDepths[637] = -1; // objDennisShelves
	global.__objectDepths[638] = 0; // objDennisTable
	global.__objectDepths[639] = 0; // objPeterCloset
	global.__objectDepths[640] = 0; // objPetersBed
	global.__objectDepths[641] = 0; // objPetersCouch
	global.__objectDepths[642] = 0; // objPetersTub
	global.__objectDepths[643] = 0; // objDennisTVBench
	global.__objectDepths[644] = 3; // objEnvelopes
	global.__objectDepths[645] = 0; // objDennisLivingRoomTable
	global.__objectDepths[646] = 3; // objFloorMail
	global.__objectDepths[647] = 0; // objAndersDrawer
	global.__objectDepths[648] = -2; // objHatRack
	global.__objectDepths[649] = 0; // objMailBoxes
	global.__objectDepths[650] = 4; // objDanceFloor
	global.__objectDepths[651] = -100; // objDiscoLights
	global.__objectDepths[652] = 0; // objDiscoLight
	global.__objectDepths[653] = 0; // objSpotlight
	global.__objectDepths[654] = 0; // objDiscoBar
	global.__objectDepths[655] = 0; // objDJRecords
	global.__objectDepths[656] = 0; // objDJTable
	global.__objectDepths[657] = 0; // objRecordPlayer
	global.__objectDepths[658] = 0; // objDiscoRoofLight
	global.__objectDepths[659] = 0; // objOldman
	global.__objectDepths[660] = 0; // objPicture
	global.__objectDepths[661] = 0; // objOldEntertainment
	global.__objectDepths[662] = 0; // objOldFountain
	global.__objectDepths[663] = 0; // objOldCouch
	global.__objectDepths[664] = 0; // objOldBed
	global.__objectDepths[665] = 0; // objOldNightstand
	global.__objectDepths[666] = 0; // objOldPhone
	global.__objectDepths[667] = 1; // objBossgun
	global.__objectDepths[668] = -2; // objBossCar1
	global.__objectDepths[669] = -2; // objBossCar2
	global.__objectDepths[670] = -2; // objCarLift
	global.__objectDepths[671] = -2; // objTyre
	global.__objectDepths[672] = -2; // objToolTable
	global.__objectDepths[673] = -2; // objWorkTable
	global.__objectDepths[674] = 0; // objBoss4Pool
	global.__objectDepths[675] = 7; // objGlassFloor
	global.__objectDepths[676] = 7; // objGlassCross
	global.__objectDepths[677] = 0; // objTrophyCabinet1
	global.__objectDepths[678] = 0; // objTrophyCabinet2
	global.__objectDepths[679] = 0; // objBoss4Sofa
	global.__objectDepths[680] = -3; // objCyanPlant
	global.__objectDepths[681] = 5; // objGlimmer
	global.__objectDepths[682] = 0; // objArcadeCabinet
	global.__objectDepths[683] = 0; // objHockeyTable
	global.__objectDepths[684] = 0; // objBasketBallGame
	global.__objectDepths[685] = -10; // objArcadeLight1
	global.__objectDepths[686] = -10; // objArcadeLight2
	global.__objectDepths[687] = 0; // objCarcade
	global.__objectDepths[688] = 0; // objClawMachine
	global.__objectDepths[689] = 0; // objFryingKitchen
	global.__objectDepths[690] = 0; // objWokKitchen
	global.__objectDepths[691] = 0; // objNoodleTable
	global.__objectDepths[692] = 0; // objGoldenCat
	global.__objectDepths[693] = 0; // objBuddha
	global.__objectDepths[694] = 0; // objChineseFishtank
	global.__objectDepths[695] = -3; // objBannerV
	global.__objectDepths[696] = 0; // objGoldenDragon
	global.__objectDepths[697] = 0; // objChineseLight
	global.__objectDepths[698] = 0; // objChineseLightBlue
	global.__objectDepths[699] = 0; // objGoldenBarBooth
	global.__objectDepths[700] = 0; // objGoldenBar
	global.__objectDepths[701] = 0; // objTruck
	global.__objectDepths[702] = 0; // objTruckFence
	global.__objectDepths[703] = 0; // objModernArt
	global.__objectDepths[704] = 0; // objFancyBar
	global.__objectDepths[705] = 1; // objWhiteBarStool
	global.__objectDepths[706] = 0; // objStage
	global.__objectDepths[707] = 0; // objStatueFence
	global.__objectDepths[708] = 0; // objSmallTable
	global.__objectDepths[709] = 0; // objClubSafe
	global.__objectDepths[710] = 0; // objOwnerDesk
	global.__objectDepths[711] = 3; // objClubSafePapers
	global.__objectDepths[712] = -1; // objClubKeys
	global.__objectDepths[713] = 0; // objClubRegister
	global.__objectDepths[714] = 0; // objPantherStatue
	global.__objectDepths[715] = 0; // objFloorTable
	global.__objectDepths[716] = 0; // objSitCushion
	global.__objectDepths[717] = 0; // objJapaneseTable
	global.__objectDepths[718] = 0; // objJapaneseLiquor
	global.__objectDepths[719] = 0; // objDrugTable
	global.__objectDepths[720] = 0; // objCocaineBox
	global.__objectDepths[721] = 0; // objCocaineCrate
	global.__objectDepths[722] = -1; // objLaser
	global.__objectDepths[723] = 0; // objBrokenWindowH
	global.__objectDepths[724] = -1; // objSwat
	global.__objectDepths[725] = 0; // objSwatOpenDoor
	global.__objectDepths[726] = 0; // objSwatSpawn
	global.__objectDepths[727] = 0; // objSwatVan
	global.__objectDepths[728] = -10; // objSwatFade
	global.__objectDepths[729] = 1; // objSwatKnockedOut
	global.__objectDepths[730] = 0; // objDrugMaterial
	global.__objectDepths[731] = 3; // objDrugSafe
	global.__objectDepths[732] = 0; // objDrugCabinet
	global.__objectDepths[733] = 0; // objShittyBar
	global.__objectDepths[734] = 0; // objShittyBarShelf
	global.__objectDepths[735] = 0; // objShittyBarTable
	global.__objectDepths[736] = 1; // objLadder
	global.__objectDepths[737] = 1001; // objSewerWaterLarge
	global.__objectDepths[738] = 1001; // objSewerWaterSmall
	global.__objectDepths[739] = 1001; // objSewerWaterMedium
	global.__objectDepths[740] = 0; // objSewerPlans
	global.__objectDepths[741] = 0; // objSewerTapes
	global.__objectDepths[742] = 0; // objSewerForms
	global.__objectDepths[743] = 0; // objSewerMasks
	global.__objectDepths[744] = 0; // objSewerPhones
	global.__objectDepths[745] = 0; // objWater
	global.__objectDepths[746] = 0; // objJanitorPhoneBox
	global.__objectDepths[747] = 0; // objJanitorBucket
	global.__objectDepths[748] = 1; // objManhole
	global.__objectDepths[749] = 0; // objManholeEquipment
	global.__objectDepths[750] = 0; // objJanitorTable
	global.__objectDepths[751] = 0; // objJanitorWorkBench
	global.__objectDepths[752] = -4; // objManholePipe
	global.__objectDepths[753] = 0; // objJanitorComputer
	global.__objectDepths[754] = 1001; // objSewerFall1
	global.__objectDepths[755] = 1001; // objSewerFall2
	global.__objectDepths[756] = -12; // objSewerShadow
	global.__objectDepths[757] = 0; // objCable1
	global.__objectDepths[758] = 0; // objCable2
	global.__objectDepths[759] = 0; // objTag
	global.__objectDepths[760] = 0; // objBigTag
	global.__objectDepths[761] = 1; // objSecretSewer
	global.__objectDepths[762] = 1; // objSewerGrate
	global.__objectDepths[763] = -12; // objSecretSewerShadow
	global.__objectDepths[764] = -1; // objNicklasStore
	global.__objectDepths[765] = -1; // objNicklasPizza
	global.__objectDepths[766] = -1; // objNicklasVHS
	global.__objectDepths[767] = -1; // objNicklasBar
	global.__objectDepths[768] = -1; // objNicklasStoreSpecial
	global.__objectDepths[769] = 2; // objNickeDead
	global.__objectDepths[770] = 2; // objNickeTiedUp
	global.__objectDepths[771] = -1; // objPrisoner
	global.__objectDepths[772] = 1; // objAssassinGround
	global.__objectDepths[773] = 1; // objAssassinDie
	global.__objectDepths[774] = -1; // objAssassinPizza
	global.__objectDepths[775] = -1; // objAssassinWait
	global.__objectDepths[776] = -1; // objAssassinSitUzi
	global.__objectDepths[777] = -1; // objAssassinVHS
	global.__objectDepths[778] = -1; // objAssassinBar
	global.__objectDepths[779] = -1; // objDreamPeople
	global.__objectDepths[780] = -1; // objDreamPlayer
	global.__objectDepths[781] = 2; // objGirlfriendDead
	global.__objectDepths[782] = 2; // objGirlfriendDeadOutline
	global.__objectDepths[783] = -1; // objGirlfriend
	global.__objectDepths[784] = -1; // objGirlfriendBathroom
	global.__objectDepths[785] = -1; // objGirlfriendSit
	global.__objectDepths[786] = -1; // objDoctorTalk
	global.__objectDepths[787] = -1; // objPoliceTalk
	global.__objectDepths[788] = -1; // objHobo
	global.__objectDepths[789] = 1; // objHoboKnockedOut
	global.__objectDepths[790] = -1; // objDeadTable
	global.__objectDepths[791] = -1; // objWileyWiggins
	global.__objectDepths[792] = -1; // objDogPetCorpse
	global.__objectDepths[793] = -1; // objFatCorpseEat
	global.__objectDepths[794] = -1; // objCrocodileMan
	global.__objectDepths[795] = 0; // objBossJacket
	global.__objectDepths[796] = 0; // objBoss1Spawn
	global.__objectDepths[797] = -1; // objBoss1
	global.__objectDepths[798] = 1; // objBoss1Down
	global.__objectDepths[799] = 0; // objBoss1Die
	global.__objectDepths[800] = 1; // objBossChair
	global.__objectDepths[801] = -1; // objBoss2
	global.__objectDepths[802] = 0; // objCleaver
	global.__objectDepths[803] = 0; // objBoss2Pry
	global.__objectDepths[804] = 0; // objBoss2GetUp
	global.__objectDepths[805] = 0; // objBoss2Crawl
	global.__objectDepths[806] = 0; // objPBashBoss2
	global.__objectDepths[807] = 1; // objBottleExplosion
	global.__objectDepths[808] = -3; // objMolotov
	global.__objectDepths[809] = 0; // objBurningGuy
	global.__objectDepths[810] = 0; // objBoss3
	global.__objectDepths[811] = 1; // objBoss3Kneel
	global.__objectDepths[812] = 1; // objBoss3Dead
	global.__objectDepths[813] = 1; // objDeadBurning
	global.__objectDepths[814] = 0; // objPlayerLighter
	global.__objectDepths[815] = -1; // objBoss4
	global.__objectDepths[816] = 1; // objBoss4Chair
	global.__objectDepths[817] = 0; // objBoss4Desk
	global.__objectDepths[818] = 0; // objBossFountain
	global.__objectDepths[819] = 0; // objBodyguard
	global.__objectDepths[820] = 2; // objPanther
	global.__objectDepths[821] = 1; // objPantherBite
	global.__objectDepths[822] = -1; // objBossPhone
	global.__objectDepths[823] = 0; // objBodyguardCrawl
	global.__objectDepths[824] = 0; // objBodyguardKnife
	global.__objectDepths[825] = -1; // objPlayerBoss
	global.__objectDepths[826] = -1; // objJanitorVacuum
	global.__objectDepths[827] = -1; // objJanitorClean
	global.__objectDepths[828] = -1; // objJanitorNotice
	global.__objectDepths[829] = -1; // objJanitorFlee
	global.__objectDepths[830] = -1; // objJanitor
	global.__objectDepths[831] = 1; // objJanitorDennisDie
	global.__objectDepths[832] = 1; // objJanitorJonatanDie
	global.__objectDepths[833] = -1; // objETauntChain
	global.__objectDepths[834] = -1; // objETauntPipe
	global.__objectDepths[835] = -1; // objETauntBat
	global.__objectDepths[836] = -1; // objVictimWall
	global.__objectDepths[837] = -1; // objETauntSmoke
	global.__objectDepths[838] = 0; // objEBombTinker
	global.__objectDepths[839] = 0; // objEStandGuardBomb
	global.__objectDepths[840] = 0; // objBombGuy
	global.__objectDepths[841] = 0; // objBombGuyDie
	global.__objectDepths[842] = 2; // objCobraDead
	global.__objectDepths[843] = 2; // objLocustDead
	global.__objectDepths[844] = 0; // objWalrusDead
	global.__objectDepths[845] = -1; // objSunAraw
	global.__objectDepths[846] = -1; // objCoconuts
	global.__objectDepths[847] = -1; // objPerturbator
	global.__objectDepths[848] = -1; // objJasper
	global.__objectDepths[849] = 2; // objMoon
	global.__objectDepths[850] = -1; // objElliott
	global.__objectDepths[851] = -1; // objScattle
	global.__objectDepths[852] = -1; // objEirik
	global.__objectDepths[853] = -1; // objGirlfriendEat
	global.__objectDepths[854] = -1; // objMCDate
	global.__objectDepths[855] = -1; // objLoneSurvivor
	global.__objectDepths[856] = 2; // objBoss2Corpse
	global.__objectDepths[857] = -1; // objDJ
	global.__objectDepths[858] = -10; // objTutorialHobo
	global.__objectDepths[859] = -2; // objOscar
	global.__objectDepths[860] = -2; // objBenjamin
	global.__objectDepths[861] = 0; // objOscarTable
	global.__objectDepths[862] = -1; // objOscarPlate
	global.__objectDepths[863] = -1; // objNigelScream
	global.__objectDepths[864] = -1; // objRasmus
	global.__objectDepths[865] = -1; // objRasmusHat
	global.__objectDepths[866] = 0; // objDevolver
	global.__objectDepths[867] = 0; // objSplash


	global.__objectNames[0] = "objPlayerMouse";
	global.__objectNames[1] = "objPlayerMouseHouse";
	global.__objectNames[2] = "objPlayerShieldMouse";
	global.__objectNames[3] = "objPlayerController";
	global.__objectNames[4] = "objMaskMenu";
	global.__objectNames[5] = "objPlayerCarEnter";
	global.__objectNames[6] = "objPlayerHospital";
	global.__objectNames[7] = "objMaskDrop";
	global.__objectNames[8] = "objPlayerDead";
	global.__objectNames[9] = "objPlayerBombDead";
	global.__objectNames[10] = "objPlayerOpenWindow";
	global.__objectNames[11] = "objPWalkWindow";
	global.__objectNames[12] = "objPlayerEnterWindow";
	global.__objectNames[13] = "objPVomit";
	global.__objectNames[14] = "objVomit";
	global.__objectNames[15] = "objPlayerTurning";
	global.__objectNames[16] = "objPlayerRipTape";
	global.__objectNames[17] = "objPoliceTape";
	global.__objectNames[18] = "objPoliceTapeRipped";
	global.__objectNames[19] = "objClubOwner";
	global.__objectNames[20] = "objPKillOwner";
	global.__objectNames[21] = "objPlayerOpenGrate";
	global.__objectNames[22] = "objPlayerClimbDown";
	global.__objectNames[23] = "objPlayerClimbUp";
	global.__objectNames[24] = "objEnemyBash";
	global.__objectNames[25] = "objPAttackThroat";
	global.__objectNames[26] = "objEnemyHeadKick";
	global.__objectNames[27] = "objPBrickKill";
	global.__objectNames[28] = "objPAttackSnap";
	global.__objectNames[29] = "objPBluntKill";
	global.__objectNames[30] = "objPAxeKill";
	global.__objectNames[31] = "objPScissorKill";
	global.__objectNames[32] = "objPSwordKill";
	global.__objectNames[33] = "objPKnifeKill";
	global.__objectNames[34] = "objPPoolKill";
	global.__objectNames[35] = "objPBrokenPoolKill";
	global.__objectNames[36] = "objPClubBoss2";
	global.__objectNames[37] = "objPHoboBash";
	global.__objectNames[38] = "objPHoboBlunt";
	global.__objectNames[39] = "objPBodyguardBlunt";
	global.__objectNames[40] = "objPBodyguardBash";
	global.__objectNames[41] = "objPDrillKill";
	global.__objectNames[42] = "objPSledgeKill";
	global.__objectNames[43] = "objPMacheteKill";
	global.__objectNames[44] = "objPBottleKill";
	global.__objectNames[45] = "objPDartKill";
	global.__objectNames[46] = "objPBoilingPotKill";
	global.__objectNames[47] = "objPKillBodyguard";
	global.__objectNames[48] = "objPHammerKill";
	global.__objectNames[49] = "objPlayerBiker";
	global.__objectNames[50] = "objPlayerBikerHouse";
	global.__objectNames[51] = "objMCBike";
	global.__objectNames[52] = "objMCHelmet";
	global.__objectNames[53] = "objThrowingKnife";
	global.__objectNames[54] = "objMCBartender";
	global.__objectNames[55] = "objBartender";
	global.__objectNames[56] = "objBikerSushi";
	global.__objectNames[57] = "objSushiGuy";
	global.__objectNames[58] = "objPlayerKneel";
	global.__objectNames[59] = "objPlayerBikerKick";
	global.__objectNames[60] = "objBikerClimbDown";
	global.__objectNames[61] = "objBikerClimbUp";
	global.__objectNames[62] = "objBikeEnding";
	global.__objectNames[63] = "objPalmTreeTop";
	global.__objectNames[64] = "objBikerKillJonatan";
	global.__objectNames[65] = "objPlayerBikerHack";
	global.__objectNames[66] = "objMCStompKill";
	global.__objectNames[67] = "objMCChopKill";
	global.__objectNames[68] = "objMCKnifeKill";
	global.__objectNames[69] = "objPigButcher";
	global.__objectNames[70] = "objPigButcherHeadbutt";
	global.__objectNames[71] = "objPigButcherKill";
	global.__objectNames[72] = "objEffector";
	global.__objectNames[73] = "objEffectorHouse";
	global.__objectNames[74] = "objEffectorHospital";
	global.__objectNames[75] = "objEffectorInstant";
	global.__objectNames[76] = "objSurfacer";
	global.__objectNames[77] = "objBackgroundColor";
	global.__objectNames[78] = "objBackgroundColorClear";
	global.__objectNames[79] = "objPlayer";
	global.__objectNames[80] = "objDoorV";
	global.__objectNames[81] = "objDoorH";
	global.__objectNames[82] = "objDoorV2";
	global.__objectNames[83] = "objDoorH2";
	global.__objectNames[84] = "objHospitalEntranceDoors";
	global.__objectNames[85] = "objWallHeavyV";
	global.__objectNames[86] = "objWallHeavyH";
	global.__objectNames[87] = "objWallSoftV";
	global.__objectNames[88] = "objWallSoftH";
	global.__objectNames[89] = "objSewerWallV";
	global.__objectNames[90] = "objSewerWallH";
	global.__objectNames[91] = "objCementWallV";
	global.__objectNames[92] = "objCementWallH";
	global.__objectNames[93] = "objCellWallV";
	global.__objectNames[94] = "objCellWallH";
	global.__objectNames[95] = "objWoodWallInteriorV";
	global.__objectNames[96] = "objWoodWallInteriorH";
	global.__objectNames[97] = "objSubwayWallV";
	global.__objectNames[98] = "objSubwayWallH";
	global.__objectNames[99] = "objPorchWallH";
	global.__objectNames[100] = "objPorchWallV";
	global.__objectNames[101] = "objWallBrickV";
	global.__objectNames[102] = "objWallBrickH";
	global.__objectNames[103] = "objWallHospitalV";
	global.__objectNames[104] = "objWallHospitalH";
	global.__objectNames[105] = "objWoodWallV";
	global.__objectNames[106] = "objWoodWallH";
	global.__objectNames[107] = "objBunkerWallH";
	global.__objectNames[108] = "objBunkerWallV";
	global.__objectNames[109] = "objFenceH";
	global.__objectNames[110] = "objFenceBroken";
	global.__objectNames[111] = "objFenceV";
	global.__objectNames[112] = "objGlassPanelV";
	global.__objectNames[113] = "objGlassPanelVBroken";
	global.__objectNames[114] = "objGlassPanelH";
	global.__objectNames[115] = "objGlassPanelHBroken";
	global.__objectNames[116] = "objWindowV";
	global.__objectNames[117] = "objWindowLargeV";
	global.__objectNames[118] = "objWindowH";
	global.__objectNames[119] = "objWindowLargeH";
	global.__objectNames[120] = "objSubwayWindowV";
	global.__objectNames[121] = "objSubwayWindowH";
	global.__objectNames[122] = "objRailV";
	global.__objectNames[123] = "objRailH";
	global.__objectNames[124] = "objWoodFenceV";
	global.__objectNames[125] = "objWoodFenceH";
	global.__objectNames[126] = "objBalconyV";
	global.__objectNames[127] = "objBalconyH";
	global.__objectNames[128] = "objBoatRailingH";
	global.__objectNames[129] = "objBoatRailingV";
	global.__objectNames[130] = "objHorBarrier";
	global.__objectNames[131] = "objVertBarrier";
	global.__objectNames[132] = "objSolid";
	global.__objectNames[133] = "objCorner";
	global.__objectNames[134] = "objTransitioner";
	global.__objectNames[135] = "objElevator";
	global.__objectNames[136] = "objPolice";
	global.__objectNames[137] = "objPolicePatrol";
	global.__objectNames[138] = "objPoliceStationary";
	global.__objectNames[139] = "objPoliceMelee";
	global.__objectNames[140] = "objPoliceMeleeStationary";
	global.__objectNames[141] = "objInspector";
	global.__objectNames[142] = "objChief";
	global.__objectNames[143] = "objPoliceHat";
	global.__objectNames[144] = "objFatmanEating";
	global.__objectNames[145] = "objFatmanTelephone";
	global.__objectNames[146] = "objFatmanShit";
	global.__objectNames[147] = "objWaiter";
	global.__objectNames[148] = "objWaiterStationary";
	global.__objectNames[149] = "objEnemyIdlePee";
	global.__objectNames[150] = "objEnemyIdleSmoke";
	global.__objectNames[151] = "objEnemySit";
	global.__objectNames[152] = "objEnemyIdleGuard";
	global.__objectNames[153] = "objEnemySitDrink";
	global.__objectNames[154] = "objEnemyDrink";
	global.__objectNames[155] = "objEnemyPhone";
	global.__objectNames[156] = "objCellPhone";
	global.__objectNames[157] = "objEnemyIdle";
	global.__objectNames[158] = "objEnemy";
	global.__objectNames[159] = "objEnemyPatrol";
	global.__objectNames[160] = "objEnemyStationary";
	global.__objectNames[161] = "objEnemyMelee";
	global.__objectNames[162] = "objEnemyMeleeStationary";
	global.__objectNames[163] = "objEHideM16";
	global.__objectNames[164] = "objDogPatrol";
	global.__objectNames[165] = "objEnemyFat";
	global.__objectNames[166] = "objEnemyMobile";
	global.__objectNames[167] = "objKnockedOut";
	global.__objectNames[168] = "objDeadBody";
	global.__objectNames[169] = "objBodyPart";
	global.__objectNames[170] = "objECrawl";
	global.__objectNames[171] = "objDogBite";
	global.__objectNames[172] = "objEnemyOld";
	global.__objectNames[173] = "objDogPatrolOld";
	global.__objectNames[174] = "objEnemyStationaryOld";
	global.__objectNames[175] = "objEnemyPatrolOld";
	global.__objectNames[176] = "objEnemyMeleeOld";
	global.__objectNames[177] = "objEnemyMobileOld";
	global.__objectNames[178] = "objEnemyMeleeStationaryOld";
	global.__objectNames[179] = "objESubwayStatic";
	global.__objectNames[180] = "objSubwayKnockedOut";
	global.__objectNames[181] = "objEGiveUp";
	global.__objectNames[182] = "objBox";
	global.__objectNames[183] = "objOpenedBox";
	global.__objectNames[184] = "objDumpster";
	global.__objectNames[185] = "objInvestigationFileSpread";
	global.__objectNames[186] = "objPlayerForm";
	global.__objectNames[187] = "objMCForm";
	global.__objectNames[188] = "objBedClip";
	global.__objectNames[189] = "objKitchenShelfClip";
	global.__objectNames[190] = "objLivingRoomClip1";
	global.__objectNames[191] = "objLivingRoomClip2";
	global.__objectNames[192] = "objTableClip";
	global.__objectNames[193] = "objKitchenCounterClip1";
	global.__objectNames[194] = "objKitchenCounterClip3";
	global.__objectNames[195] = "objKitchenCounterClip2";
	global.__objectNames[196] = "objBriefcase";
	global.__objectNames[197] = "objVHSTake";
	global.__objectNames[198] = "objPizzaTake";
	global.__objectNames[199] = "objDrink";
	global.__objectNames[200] = "objSixpack";
	global.__objectNames[201] = "objChipsBag";
	global.__objectNames[202] = "objKeys";
	global.__objectNames[203] = "objPlayerJacket";
	global.__objectNames[204] = "objPlayerPants";
	global.__objectNames[205] = "objToken";
	global.__objectNames[206] = "objSecretMask";
	global.__objectNames[207] = "objWeapon";
	global.__objectNames[208] = "objSpecificWeapon";
	global.__objectNames[209] = "objWeaponThrow";
	global.__objectNames[210] = "objThrowingWeapon";
	global.__objectNames[211] = "objBullet";
	global.__objectNames[212] = "objEBullet";
	global.__objectNames[213] = "objBulletHit";
	global.__objectNames[214] = "objBloodDrop2";
	global.__objectNames[215] = "objBloodCut";
	global.__objectNames[216] = "objBloodHit";
	global.__objectNames[217] = "objBloodSmoke2";
	global.__objectNames[218] = "objBulleter";
	global.__objectNames[219] = "objBloodSplat2";
	global.__objectNames[220] = "objBrains2";
	global.__objectNames[221] = "objBrainChunk2";
	global.__objectNames[222] = "objGuts2";
	global.__objectNames[223] = "objSkinPiece2";
	global.__objectNames[224] = "objBloodSmoke";
	global.__objectNames[225] = "objBloodSplat";
	global.__objectNames[226] = "objBloodDrop";
	global.__objectNames[227] = "objBloodPool";
	global.__objectNames[228] = "objBloodSquirt";
	global.__objectNames[229] = "objBrains";
	global.__objectNames[230] = "objHit";
	global.__objectNames[231] = "objSmokeHit";
	global.__objectNames[232] = "objShell";
	global.__objectNames[233] = "objDebris";
	global.__objectNames[234] = "objShard";
	global.__objectNames[235] = "objTinyShard";
	global.__objectNames[236] = "objFlies";
	global.__objectNames[237] = "objSteam";
	global.__objectNames[238] = "objPWater";
	global.__objectNames[239] = "objSpark2";
	global.__objectNames[240] = "objSpark1";
	global.__objectNames[241] = "objBombGround";
	global.__objectNames[242] = "objFloatingBottle";
	global.__objectNames[243] = "objClip";
	global.__objectNames[244] = "objDriveSmoke";
	global.__objectNames[245] = "objBrokenBottle";
	global.__objectNames[246] = "objTitle";
	global.__objectNames[247] = "objPalmTree";
	global.__objectNames[248] = "objHouse";
	global.__objectNames[249] = "objLevelSelect";
	global.__objectNames[250] = "objShowControls";
	global.__objectNames[251] = "objPause";
	global.__objectNames[252] = "objScore";
	global.__objectNames[253] = "objLevelComplete";
	global.__objectNames[254] = "objMaskUnlock";
	global.__objectNames[255] = "objWeaponUnlock";
	global.__objectNames[256] = "objLevelTitle";
	global.__objectNames[257] = "objMCLevelTitle";
	global.__objectNames[258] = "objHospitalTitle";
	global.__objectNames[259] = "objPartTitle";
	global.__objectNames[260] = "objInterlude";
	global.__objectNames[261] = "objBandCredits";
	global.__objectNames[262] = "objWave";
	global.__objectNames[263] = "objCredits";
	global.__objectNames[264] = "objSpread";
	global.__objectNames[265] = "objLightingEngine";
	global.__objectNames[266] = "objLight";
	global.__objectNames[267] = "objLightingNormal";
	global.__objectNames[268] = "objLightNormal";
	global.__objectNames[269] = "objLetterSocket";
	global.__objectNames[270] = "objLetter";
	global.__objectNames[271] = "objPuzzle";
	global.__objectNames[272] = "objLetterDone";
	global.__objectNames[273] = "objLetterFound";
	global.__objectNames[274] = "sxms";
	global.__objectNames[275] = "objVCapture";
	global.__objectNames[276] = "objPathTest";
	global.__objectNames[277] = "objShadowH";
	global.__objectNames[278] = "objShadowV";
	global.__objectNames[279] = "objShootThrough";
	global.__objectNames[280] = "objFurniture";
	global.__objectNames[281] = "objPhoneConversation";
	global.__objectNames[282] = "objSurfaceReturn";
	global.__objectNames[283] = "objTeleporter";
	global.__objectNames[284] = "objScoreStats";
	global.__objectNames[285] = "objBoss";
	global.__objectNames[286] = "objHouseReturn";
	global.__objectNames[287] = "objCheckpoint";
	global.__objectNames[288] = "objExporter";
	global.__objectNames[289] = "objTrainshake";
	global.__objectNames[290] = "objElectricLight";
	global.__objectNames[291] = "objHospitalTransition";
	global.__objectNames[292] = "objHospitalTalk";
	global.__objectNames[293] = "objDizzy";
	global.__objectNames[294] = "objEmpty";
	global.__objectNames[295] = "objMiscEnemy";
	global.__objectNames[296] = "objFlameParticle";
	global.__objectNames[297] = "objBoss3Spawn";
	global.__objectNames[298] = "objSequence12Light";
	global.__objectNames[299] = "objTutorialLight";
	global.__objectNames[300] = "objGoToCar";
	global.__objectNames[301] = "objScoreDetails";
	global.__objectNames[302] = "objSunSparkle";
	global.__objectNames[303] = "objDateRewind";
	global.__objectNames[304] = "objFinalDialogue";
	global.__objectNames[305] = "objFinalDialogue2";
	global.__objectNames[306] = "objAlienWare";
	global.__objectNames[307] = "objSteamQuestion";
	global.__objectNames[308] = "objFocus";
	global.__objectNames[309] = "objTub";
	global.__objectNames[310] = "objSink";
	global.__objectNames[311] = "objUrinalV";
	global.__objectNames[312] = "objToilet";
	global.__objectNames[313] = "objShowerCurtain";
	global.__objectNames[314] = "objJacuzzi";
	global.__objectNames[315] = "objShowerGlassV";
	global.__objectNames[316] = "objShowerGlassH";
	global.__objectNames[317] = "objShowerGlassDoor";
	global.__objectNames[318] = "objHotelSuiteTub";
	global.__objectNames[319] = "objHotelSink";
	global.__objectNames[320] = "objHotelSuiteToilet";
	global.__objectNames[321] = "objChair";
	global.__objectNames[322] = "objShelves";
	global.__objectNames[323] = "objKitchenSink";
	global.__objectNames[324] = "objStove";
	global.__objectNames[325] = "objTable";
	global.__objectNames[326] = "objMicrowave";
	global.__objectNames[327] = "objFridge";
	global.__objectNames[328] = "objToyBall";
	global.__objectNames[329] = "objToyTurtle";
	global.__objectNames[330] = "objToyBear";
	global.__objectNames[331] = "objToyLego";
	global.__objectNames[332] = "objToyM16";
	global.__objectNames[333] = "objToyMP5";
	global.__objectNames[334] = "objPelletsCorner";
	global.__objectNames[335] = "objPelletsSide";
	global.__objectNames[336] = "objPellets";
	global.__objectNames[337] = "objPelletPlant";
	global.__objectNames[338] = "objPlant";
	global.__objectNames[339] = "objHospitalPlant";
	global.__objectNames[340] = "objPizza";
	global.__objectNames[341] = "objTrashbag";
	global.__objectNames[342] = "objTrashcan";
	global.__objectNames[343] = "objBurningTrashcan";
	global.__objectNames[344] = "objHomelessBed";
	global.__objectNames[345] = "objSofaV64";
	global.__objectNames[346] = "objSofaV48";
	global.__objectNames[347] = "objSofaH64";
	global.__objectNames[348] = "objDrawerV24";
	global.__objectNames[349] = "objDrawerH24";
	global.__objectNames[350] = "objSofaH48";
	global.__objectNames[351] = "objShirts";
	global.__objectNames[352] = "objCassetteDeck";
	global.__objectNames[353] = "objComputer";
	global.__objectNames[354] = "objVinylRecord";
	global.__objectNames[355] = "objBigTable";
	global.__objectNames[356] = "objBeds";
	global.__objectNames[357] = "objLamps";
	global.__objectNames[358] = "objJackets";
	global.__objectNames[359] = "objNes";
	global.__objectNames[360] = "objVinylPlayer";
	global.__objectNames[361] = "objSpeaker";
	global.__objectNames[362] = "objTVBlack";
	global.__objectNames[363] = "objTigerCarpet";
	global.__objectNames[364] = "objFountain";
	global.__objectNames[365] = "objBigBed";
	global.__objectNames[366] = "objLeatherCouch";
	global.__objectNames[367] = "objPoolTable";
	global.__objectNames[368] = "objGlassTable";
	global.__objectNames[369] = "objNightStand";
	global.__objectNames[370] = "objTrophyHead";
	global.__objectNames[371] = "objWineRack";
	global.__objectNames[372] = "objCouchCushion";
	global.__objectNames[373] = "objArmchair";
	global.__objectNames[374] = "objRichTable";
	global.__objectNames[375] = "objDiningChair";
	global.__objectNames[376] = "objLaundryBasket";
	global.__objectNames[377] = "objCarBottom";
	global.__objectNames[378] = "objAquarium";
	global.__objectNames[379] = "objAquariumBreak";
	global.__objectNames[380] = "objAquariumWater";
	global.__objectNames[381] = "objPhone";
	global.__objectNames[382] = "objVendingMachine";
	global.__objectNames[383] = "objTVWallMounted";
	global.__objectNames[384] = "objLockerH";
	global.__objectNames[385] = "objLockerV";
	global.__objectNames[386] = "objSubwayBenchV";
	global.__objectNames[387] = "objSubwayBench";
	global.__objectNames[388] = "objTrain";
	global.__objectNames[389] = "objSubwayDoor";
	global.__objectNames[390] = "objClotheslineH";
	global.__objectNames[391] = "objClotheslineV";
	global.__objectNames[392] = "objAnsweringMachine";
	global.__objectNames[393] = "objPlayerBed1";
	global.__objectNames[394] = "objPlayerBed2";
	global.__objectNames[395] = "objPlayerCouch";
	global.__objectNames[396] = "objPlayerKitchenCounter";
	global.__objectNames[397] = "objPlayerKitchenShelf";
	global.__objectNames[398] = "objPlayerKitchenSink";
	global.__objectNames[399] = "objPlayerLivingRoomTable";
	global.__objectNames[400] = "objPlayerFridge";
	global.__objectNames[401] = "objPlayerTable";
	global.__objectNames[402] = "objVomitBucket";
	global.__objectNames[403] = "objPlayerTub";
	global.__objectNames[404] = "objGate";
	global.__objectNames[405] = "objMonitors";
	global.__objectNames[406] = "objPornBed";
	global.__objectNames[407] = "objPornCamera";
	global.__objectNames[408] = "objPornLight";
	global.__objectNames[409] = "objPoliceDesk";
	global.__objectNames[410] = "objPoliceDeskPuter";
	global.__objectNames[411] = "objInterrogationTable";
	global.__objectNames[412] = "objSpeakerBooth";
	global.__objectNames[413] = "objPoliceArmchair";
	global.__objectNames[414] = "objPoliceDeskChair";
	global.__objectNames[415] = "objMetalDetector";
	global.__objectNames[416] = "objPaperbin";
	global.__objectNames[417] = "objPoliceSofa";
	global.__objectNames[418] = "objFiles";
	global.__objectNames[419] = "objFileCabinet";
	global.__objectNames[420] = "objPoliceFrontDesk";
	global.__objectNames[421] = "objPoliceEntryDesk";
	global.__objectNames[422] = "objBigPoliceTable";
	global.__objectNames[423] = "objEvidenceTable";
	global.__objectNames[424] = "objSurveillanceCamera";
	global.__objectNames[425] = "objCellBed";
	global.__objectNames[426] = "objCellSink";
	global.__objectNames[427] = "objCellToilet";
	global.__objectNames[428] = "objCellDoor";
	global.__objectNames[429] = "objSurveillanceCenter";
	global.__objectNames[430] = "objBarricade1";
	global.__objectNames[431] = "objBarricade2";
	global.__objectNames[432] = "objCopCar";
	global.__objectNames[433] = "objPhoneRecorder";
	global.__objectNames[434] = "objPhoneTable";
	global.__objectNames[435] = "objPhone1";
	global.__objectNames[436] = "objPhone2";
	global.__objectNames[437] = "objTowels";
	global.__objectNames[438] = "objWaterPuddle";
	global.__objectNames[439] = "objBubbleBath";
	global.__objectNames[440] = "objGymLocker";
	global.__objectNames[441] = "objSaunaBench";
	global.__objectNames[442] = "objSunChair";
	global.__objectNames[443] = "objSolarium";
	global.__objectNames[444] = "objSolariumOpen";
	global.__objectNames[445] = "objHeater";
	global.__objectNames[446] = "objGymBench";
	global.__objectNames[447] = "objSaunaSteam";
	global.__objectNames[448] = "objCandleTable";
	global.__objectNames[449] = "objCandleTableBurning";
	global.__objectNames[450] = "objMassageTable";
	global.__objectNames[451] = "objEnormousFountain";
	global.__objectNames[452] = "objSaunaCurtain";
	global.__objectNames[453] = "objSaunaCounter";
	global.__objectNames[454] = "objSaunaFountain";
	global.__objectNames[455] = "objYinYang";
	global.__objectNames[456] = "objCeoTable";
	global.__objectNames[457] = "objReceptionDesk";
	global.__objectNames[458] = "objPhoneHom";
	global.__objectNames[459] = "objCeoDead";
	global.__objectNames[460] = "objEmployeeDead";
	global.__objectNames[461] = "objEmployeeDeadPiece";
	global.__objectNames[462] = "objEmployeeDeadWall";
	global.__objectNames[463] = "objWorkerdDead";
	global.__objectNames[464] = "objGolfBag";
	global.__objectNames[465] = "objWorker";
	global.__objectNames[466] = "objEmployee";
	global.__objectNames[467] = "objCEO";
	global.__objectNames[468] = "objPhoneHomSafe";
	global.__objectNames[469] = "objPhoneHomPainting";
	global.__objectNames[470] = "objPhoneHomPaintingWall";
	global.__objectNames[471] = "objGolfCourt";
	global.__objectNames[472] = "objNiklasFridge";
	global.__objectNames[473] = "objFreezer";
	global.__objectNames[474] = "objStoreShelf";
	global.__objectNames[475] = "objStoreFridge";
	global.__objectNames[476] = "objRegister";
	global.__objectNames[477] = "objDoubleFridge";
	global.__objectNames[478] = "objNeonSign";
	global.__objectNames[479] = "objFan";
	global.__objectNames[480] = "objStorePapers";
	global.__objectNames[481] = "objPizzaRegister";
	global.__objectNames[482] = "objPizzaOven";
	global.__objectNames[483] = "objPizzaDisplay";
	global.__objectNames[484] = "objPizzaCounter";
	global.__objectNames[485] = "objPizzaTable";
	global.__objectNames[486] = "sprVHSDoorMat";
	global.__objectNames[487] = "objVHSRackH";
	global.__objectNames[488] = "objVHSRackV";
	global.__objectNames[489] = "objVHSTape";
	global.__objectNames[490] = "objVHSCounter";
	global.__objectNames[491] = "objVHSArchive";
	global.__objectNames[492] = "objBarPlant";
	global.__objectNames[493] = "objBarBooth";
	global.__objectNames[494] = "objBarStool";
	global.__objectNames[495] = "objBarRegister";
	global.__objectNames[496] = "objBarShelf";
	global.__objectNames[497] = "objJukebox";
	global.__objectNames[498] = "objBarTable";
	global.__objectNames[499] = "objBarPoolTable";
	global.__objectNames[500] = "objPhoneBooth";
	global.__objectNames[501] = "objHospitalChair";
	global.__objectNames[502] = "objHospitalBed";
	global.__objectNames[503] = "objHospitalBedStand";
	global.__objectNames[504] = "objHospitalCouch";
	global.__objectNames[505] = "objHospitalCouch2";
	global.__objectNames[506] = "objWheelChair";
	global.__objectNames[507] = "objHospitalDesk";
	global.__objectNames[508] = "objHospitalCupboard";
	global.__objectNames[509] = "objHospitalCurtains";
	global.__objectNames[510] = "objHospitalLocker";
	global.__objectNames[511] = "objHospitalSofaV";
	global.__objectNames[512] = "objHospitalSofaH";
	global.__objectNames[513] = "objHospitalElevator";
	global.__objectNames[514] = "objWindowOpen";
	global.__objectNames[515] = "objDoctorPatrol";
	global.__objectNames[516] = "objPoliceRead";
	global.__objectNames[517] = "objKeycard";
	global.__objectNames[518] = "objLockedDoor";
	global.__objectNames[519] = "objHandicapToilet";
	global.__objectNames[520] = "objHospitalReception";
	global.__objectNames[521] = "objGargoyle";
	global.__objectNames[522] = "objXray";
	global.__objectNames[523] = "objExamTable";
	global.__objectNames[524] = "objHospitalStaffSofa";
	global.__objectNames[525] = "objHospitalStaffMicro";
	global.__objectNames[526] = "objHospitalStaffTable";
	global.__objectNames[527] = "objRestaurantChair";
	global.__objectNames[528] = "objWineBottle";
	global.__objectNames[529] = "objBuffe";
	global.__objectNames[530] = "objFoodTray";
	global.__objectNames[531] = "objBuffePlates";
	global.__objectNames[532] = "objHotelSuiteSofa";
	global.__objectNames[533] = "objHotelSuiteChair";
	global.__objectNames[534] = "objHotelSuiteEntertainment";
	global.__objectNames[535] = "objHotelSimpleBed";
	global.__objectNames[536] = "objRestaurantTable";
	global.__objectNames[537] = "objHotelNightStandLight";
	global.__objectNames[538] = "objHotelNightStand";
	global.__objectNames[539] = "objHotelSuiteBed";
	global.__objectNames[540] = "objMinibar";
	global.__objectNames[541] = "objCleaningCart";
	global.__objectNames[542] = "objHotelCloset";
	global.__objectNames[543] = "objFootstand";
	global.__objectNames[544] = "objHotelChair";
	global.__objectNames[545] = "objWetSpot";
	global.__objectNames[546] = "objWetFloorWarning";
	global.__objectNames[547] = "objPoolTray";
	global.__objectNames[548] = "objPool";
	global.__objectNames[549] = "objPoolChair";
	global.__objectNames[550] = "objFireAxe";
	global.__objectNames[551] = "objKaraokeCouchPink";
	global.__objectNames[552] = "objKaraokeCouchBlack";
	global.__objectNames[553] = "objSpeakerTable";
	global.__objectNames[554] = "objKaraokeMachine";
	global.__objectNames[555] = "objHighballBooth";
	global.__objectNames[556] = "objLaneStart";
	global.__objectNames[557] = "objBowlingLane";
	global.__objectNames[558] = "objBowlingEnd";
	global.__objectNames[559] = "objLaptopTable";
	global.__objectNames[560] = "objHighballBoothBlack";
	global.__objectNames[561] = "objHighballChair";
	global.__objectNames[562] = "objSquareTable";
	global.__objectNames[563] = "objHighballCurtain";
	global.__objectNames[564] = "objHighballDiningChair";
	global.__objectNames[565] = "objHighballSign";
	global.__objectNames[566] = "objHighballBar";
	global.__objectNames[567] = "objVenuspatrol";
	global.__objectNames[568] = "objVenuspetrol";
	global.__objectNames[569] = "objVenuspatrolChalk";
	global.__objectNames[570] = "objBrandon";
	global.__objectNames[571] = "objSacrifice";
	global.__objectNames[572] = "objVenusPatrolSmall";
	global.__objectNames[573] = "objVenusCandle";
	global.__objectNames[574] = "objStroller";
	global.__objectNames[575] = "objEuroLogo";
	global.__objectNames[576] = "objBallOfDuty";
	global.__objectNames[577] = "objAssassinsBreed";
	global.__objectNames[578] = "object707";
	global.__objectNames[579] = "objRezzed";
	global.__objectNames[580] = "objHotlineLogo";
	global.__objectNames[581] = "objEuroPodV";
	global.__objectNames[582] = "objEuroPodH";
	global.__objectNames[583] = "objEuroFenceH";
	global.__objectNames[584] = "objEuroFenceV";
	global.__objectNames[585] = "objEuroPillar";
	global.__objectNames[586] = "objEuroIce";
	global.__objectNames[587] = "objEuroTrash";
	global.__objectNames[588] = "objPimpToilet";
	global.__objectNames[589] = "objBlackTub";
	global.__objectNames[590] = "objPimpSink";
	global.__objectNames[591] = "objMCKitchenShelf";
	global.__objectNames[592] = "objMCKitchenSink";
	global.__objectNames[593] = "objMCBed";
	global.__objectNames[594] = "objMCComputer";
	global.__objectNames[595] = "objMCCouch";
	global.__objectNames[596] = "objMCStereo";
	global.__objectNames[597] = "objMCGlassTable";
	global.__objectNames[598] = "objMCKeytar";
	global.__objectNames[599] = "objMCSkateboard";
	global.__objectNames[600] = "objMCStatue";
	global.__objectNames[601] = "objMCStove";
	global.__objectNames[602] = "objMCRecords";
	global.__objectNames[603] = "objUnderwear";
	global.__objectNames[604] = "objShoes";
	global.__objectNames[605] = "objMCTVTable";
	global.__objectNames[606] = "objMCTigerCarpet";
	global.__objectNames[607] = "objMCAquarium";
	global.__objectNames[608] = "objPimpPhone";
	global.__objectNames[609] = "objMCBottle";
	global.__objectNames[610] = "objProjector";
	global.__objectNames[611] = "objProjectorLight";
	global.__objectNames[612] = "objCopyMachine";
	global.__objectNames[613] = "objFileCabinetOffice";
	global.__objectNames[614] = "objConferenceTable";
	global.__objectNames[615] = "objOfficeCouch";
	global.__objectNames[616] = "objOfficeDesk";
	global.__objectNames[617] = "objOfficeCouchSmall";
	global.__objectNames[618] = "objProjectorTable";
	global.__objectNames[619] = "objVan";
	global.__objectNames[620] = "objGlassPanelDestroyedH";
	global.__objectNames[621] = "objGlassPanelDestroyedV";
	global.__objectNames[622] = "objOfficeDoor";
	global.__objectNames[623] = "objVanBottom";
	global.__objectNames[624] = "objExplosion";
	global.__objectNames[625] = "objBombCables";
	global.__objectNames[626] = "objDestroyedDoor";
	global.__objectNames[627] = "objDoorDebris";
	global.__objectNames[628] = "objWindowExplode";
	global.__objectNames[629] = "objTableBarricade";
	global.__objectNames[630] = "objDennisCouch";
	global.__objectNames[631] = "objAndersBed";
	global.__objectNames[632] = "objAndersCouch";
	global.__objectNames[633] = "objAndersDesk";
	global.__objectNames[634] = "objAndersTable";
	global.__objectNames[635] = "objLitterBox";
	global.__objectNames[636] = "objDennisBed";
	global.__objectNames[637] = "objDennisShelves";
	global.__objectNames[638] = "objDennisTable";
	global.__objectNames[639] = "objPeterCloset";
	global.__objectNames[640] = "objPetersBed";
	global.__objectNames[641] = "objPetersCouch";
	global.__objectNames[642] = "objPetersTub";
	global.__objectNames[643] = "objDennisTVBench";
	global.__objectNames[644] = "objEnvelopes";
	global.__objectNames[645] = "objDennisLivingRoomTable";
	global.__objectNames[646] = "objFloorMail";
	global.__objectNames[647] = "objAndersDrawer";
	global.__objectNames[648] = "objHatRack";
	global.__objectNames[649] = "objMailBoxes";
	global.__objectNames[650] = "objDanceFloor";
	global.__objectNames[651] = "objDiscoLights";
	global.__objectNames[652] = "objDiscoLight";
	global.__objectNames[653] = "objSpotlight";
	global.__objectNames[654] = "objDiscoBar";
	global.__objectNames[655] = "objDJRecords";
	global.__objectNames[656] = "objDJTable";
	global.__objectNames[657] = "objRecordPlayer";
	global.__objectNames[658] = "objDiscoRoofLight";
	global.__objectNames[659] = "objOldman";
	global.__objectNames[660] = "objPicture";
	global.__objectNames[661] = "objOldEntertainment";
	global.__objectNames[662] = "objOldFountain";
	global.__objectNames[663] = "objOldCouch";
	global.__objectNames[664] = "objOldBed";
	global.__objectNames[665] = "objOldNightstand";
	global.__objectNames[666] = "objOldPhone";
	global.__objectNames[667] = "objBossgun";
	global.__objectNames[668] = "objBossCar1";
	global.__objectNames[669] = "objBossCar2";
	global.__objectNames[670] = "objCarLift";
	global.__objectNames[671] = "objTyre";
	global.__objectNames[672] = "objToolTable";
	global.__objectNames[673] = "objWorkTable";
	global.__objectNames[674] = "objBoss4Pool";
	global.__objectNames[675] = "objGlassFloor";
	global.__objectNames[676] = "objGlassCross";
	global.__objectNames[677] = "objTrophyCabinet1";
	global.__objectNames[678] = "objTrophyCabinet2";
	global.__objectNames[679] = "objBoss4Sofa";
	global.__objectNames[680] = "objCyanPlant";
	global.__objectNames[681] = "objGlimmer";
	global.__objectNames[682] = "objArcadeCabinet";
	global.__objectNames[683] = "objHockeyTable";
	global.__objectNames[684] = "objBasketBallGame";
	global.__objectNames[685] = "objArcadeLight1";
	global.__objectNames[686] = "objArcadeLight2";
	global.__objectNames[687] = "objCarcade";
	global.__objectNames[688] = "objClawMachine";
	global.__objectNames[689] = "objFryingKitchen";
	global.__objectNames[690] = "objWokKitchen";
	global.__objectNames[691] = "objNoodleTable";
	global.__objectNames[692] = "objGoldenCat";
	global.__objectNames[693] = "objBuddha";
	global.__objectNames[694] = "objChineseFishtank";
	global.__objectNames[695] = "objBannerV";
	global.__objectNames[696] = "objGoldenDragon";
	global.__objectNames[697] = "objChineseLight";
	global.__objectNames[698] = "objChineseLightBlue";
	global.__objectNames[699] = "objGoldenBarBooth";
	global.__objectNames[700] = "objGoldenBar";
	global.__objectNames[701] = "objTruck";
	global.__objectNames[702] = "objTruckFence";
	global.__objectNames[703] = "objModernArt";
	global.__objectNames[704] = "objFancyBar";
	global.__objectNames[705] = "objWhiteBarStool";
	global.__objectNames[706] = "objStage";
	global.__objectNames[707] = "objStatueFence";
	global.__objectNames[708] = "objSmallTable";
	global.__objectNames[709] = "objClubSafe";
	global.__objectNames[710] = "objOwnerDesk";
	global.__objectNames[711] = "objClubSafePapers";
	global.__objectNames[712] = "objClubKeys";
	global.__objectNames[713] = "objClubRegister";
	global.__objectNames[714] = "objPantherStatue";
	global.__objectNames[715] = "objFloorTable";
	global.__objectNames[716] = "objSitCushion";
	global.__objectNames[717] = "objJapaneseTable";
	global.__objectNames[718] = "objJapaneseLiquor";
	global.__objectNames[719] = "objDrugTable";
	global.__objectNames[720] = "objCocaineBox";
	global.__objectNames[721] = "objCocaineCrate";
	global.__objectNames[722] = "objLaser";
	global.__objectNames[723] = "objBrokenWindowH";
	global.__objectNames[724] = "objSwat";
	global.__objectNames[725] = "objSwatOpenDoor";
	global.__objectNames[726] = "objSwatSpawn";
	global.__objectNames[727] = "objSwatVan";
	global.__objectNames[728] = "objSwatFade";
	global.__objectNames[729] = "objSwatKnockedOut";
	global.__objectNames[730] = "objDrugMaterial";
	global.__objectNames[731] = "objDrugSafe";
	global.__objectNames[732] = "objDrugCabinet";
	global.__objectNames[733] = "objShittyBar";
	global.__objectNames[734] = "objShittyBarShelf";
	global.__objectNames[735] = "objShittyBarTable";
	global.__objectNames[736] = "objLadder";
	global.__objectNames[737] = "objSewerWaterLarge";
	global.__objectNames[738] = "objSewerWaterSmall";
	global.__objectNames[739] = "objSewerWaterMedium";
	global.__objectNames[740] = "objSewerPlans";
	global.__objectNames[741] = "objSewerTapes";
	global.__objectNames[742] = "objSewerForms";
	global.__objectNames[743] = "objSewerMasks";
	global.__objectNames[744] = "objSewerPhones";
	global.__objectNames[745] = "objWater";
	global.__objectNames[746] = "objJanitorPhoneBox";
	global.__objectNames[747] = "objJanitorBucket";
	global.__objectNames[748] = "objManhole";
	global.__objectNames[749] = "objManholeEquipment";
	global.__objectNames[750] = "objJanitorTable";
	global.__objectNames[751] = "objJanitorWorkBench";
	global.__objectNames[752] = "objManholePipe";
	global.__objectNames[753] = "objJanitorComputer";
	global.__objectNames[754] = "objSewerFall1";
	global.__objectNames[755] = "objSewerFall2";
	global.__objectNames[756] = "objSewerShadow";
	global.__objectNames[757] = "objCable1";
	global.__objectNames[758] = "objCable2";
	global.__objectNames[759] = "objTag";
	global.__objectNames[760] = "objBigTag";
	global.__objectNames[761] = "objSecretSewer";
	global.__objectNames[762] = "objSewerGrate";
	global.__objectNames[763] = "objSecretSewerShadow";
	global.__objectNames[764] = "objNicklasStore";
	global.__objectNames[765] = "objNicklasPizza";
	global.__objectNames[766] = "objNicklasVHS";
	global.__objectNames[767] = "objNicklasBar";
	global.__objectNames[768] = "objNicklasStoreSpecial";
	global.__objectNames[769] = "objNickeDead";
	global.__objectNames[770] = "objNickeTiedUp";
	global.__objectNames[771] = "objPrisoner";
	global.__objectNames[772] = "objAssassinGround";
	global.__objectNames[773] = "objAssassinDie";
	global.__objectNames[774] = "objAssassinPizza";
	global.__objectNames[775] = "objAssassinWait";
	global.__objectNames[776] = "objAssassinSitUzi";
	global.__objectNames[777] = "objAssassinVHS";
	global.__objectNames[778] = "objAssassinBar";
	global.__objectNames[779] = "objDreamPeople";
	global.__objectNames[780] = "objDreamPlayer";
	global.__objectNames[781] = "objGirlfriendDead";
	global.__objectNames[782] = "objGirlfriendDeadOutline";
	global.__objectNames[783] = "objGirlfriend";
	global.__objectNames[784] = "objGirlfriendBathroom";
	global.__objectNames[785] = "objGirlfriendSit";
	global.__objectNames[786] = "objDoctorTalk";
	global.__objectNames[787] = "objPoliceTalk";
	global.__objectNames[788] = "objHobo";
	global.__objectNames[789] = "objHoboKnockedOut";
	global.__objectNames[790] = "objDeadTable";
	global.__objectNames[791] = "objWileyWiggins";
	global.__objectNames[792] = "objDogPetCorpse";
	global.__objectNames[793] = "objFatCorpseEat";
	global.__objectNames[794] = "objCrocodileMan";
	global.__objectNames[795] = "objBossJacket";
	global.__objectNames[796] = "objBoss1Spawn";
	global.__objectNames[797] = "objBoss1";
	global.__objectNames[798] = "objBoss1Down";
	global.__objectNames[799] = "objBoss1Die";
	global.__objectNames[800] = "objBossChair";
	global.__objectNames[801] = "objBoss2";
	global.__objectNames[802] = "objCleaver";
	global.__objectNames[803] = "objBoss2Pry";
	global.__objectNames[804] = "objBoss2GetUp";
	global.__objectNames[805] = "objBoss2Crawl";
	global.__objectNames[806] = "objPBashBoss2";
	global.__objectNames[807] = "objBottleExplosion";
	global.__objectNames[808] = "objMolotov";
	global.__objectNames[809] = "objBurningGuy";
	global.__objectNames[810] = "objBoss3";
	global.__objectNames[811] = "objBoss3Kneel";
	global.__objectNames[812] = "objBoss3Dead";
	global.__objectNames[813] = "objDeadBurning";
	global.__objectNames[814] = "objPlayerLighter";
	global.__objectNames[815] = "objBoss4";
	global.__objectNames[816] = "objBoss4Chair";
	global.__objectNames[817] = "objBoss4Desk";
	global.__objectNames[818] = "objBossFountain";
	global.__objectNames[819] = "objBodyguard";
	global.__objectNames[820] = "objPanther";
	global.__objectNames[821] = "objPantherBite";
	global.__objectNames[822] = "objBossPhone";
	global.__objectNames[823] = "objBodyguardCrawl";
	global.__objectNames[824] = "objBodyguardKnife";
	global.__objectNames[825] = "objPlayerBoss";
	global.__objectNames[826] = "objJanitorVacuum";
	global.__objectNames[827] = "objJanitorClean";
	global.__objectNames[828] = "objJanitorNotice";
	global.__objectNames[829] = "objJanitorFlee";
	global.__objectNames[830] = "objJanitor";
	global.__objectNames[831] = "objJanitorDennisDie";
	global.__objectNames[832] = "objJanitorJonatanDie";
	global.__objectNames[833] = "objETauntChain";
	global.__objectNames[834] = "objETauntPipe";
	global.__objectNames[835] = "objETauntBat";
	global.__objectNames[836] = "objVictimWall";
	global.__objectNames[837] = "objETauntSmoke";
	global.__objectNames[838] = "objEBombTinker";
	global.__objectNames[839] = "objEStandGuardBomb";
	global.__objectNames[840] = "objBombGuy";
	global.__objectNames[841] = "objBombGuyDie";
	global.__objectNames[842] = "objCobraDead";
	global.__objectNames[843] = "objLocustDead";
	global.__objectNames[844] = "objWalrusDead";
	global.__objectNames[845] = "objSunAraw";
	global.__objectNames[846] = "objCoconuts";
	global.__objectNames[847] = "objPerturbator";
	global.__objectNames[848] = "objJasper";
	global.__objectNames[849] = "objMoon";
	global.__objectNames[850] = "objElliott";
	global.__objectNames[851] = "objScattle";
	global.__objectNames[852] = "objEirik";
	global.__objectNames[853] = "objGirlfriendEat";
	global.__objectNames[854] = "objMCDate";
	global.__objectNames[855] = "objLoneSurvivor";
	global.__objectNames[856] = "objBoss2Corpse";
	global.__objectNames[857] = "objDJ";
	global.__objectNames[858] = "objTutorialHobo";
	global.__objectNames[859] = "objOscar";
	global.__objectNames[860] = "objBenjamin";
	global.__objectNames[861] = "objOscarTable";
	global.__objectNames[862] = "objOscarPlate";
	global.__objectNames[863] = "objNigelScream";
	global.__objectNames[864] = "objRasmus";
	global.__objectNames[865] = "objRasmusHat";
	global.__objectNames[866] = "objDevolver";
	global.__objectNames[867] = "objSplash";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
