i=0
global.currentlevel=0
repeat (16) {
global.levelscore[i]=0
i+=1
}
global.drawscore=0
global.myscore=0
global.combotime=0
global.comboscore=0
global.killscore=0
global.boldscore=0
global.timescore=0
global.flexibilityscore=0
global.mobilityscore=0
global.specialscore=0
global.noguns=1
global.barehanded=1
global.switchweapon=1
global.neverseen=1
global.nomiss=1
global.oneweapon=1
global.punchonly=1
global.combo=0
global.kills=0
global.gunkill=0
global.time=0
i=0 
repeat (39) {
global.flexibility[i]=0
i+=1
}
