/*if global.surfaces=1 {
set_automatic_draw(false)
tile_layer_show(1000)
tile_layer_hide(1002)
tile_layer_show(1000000)
draw_clear_alpha(make_color_hsv(0,0,2),0)
background_showcolor=0
view_enabled=0
view_visible[0]=0*/
//screen_refresh()
/*instance_deactivate_all(true)
surf1=surface_create(room_width,room_height)
surface_set_target(surf1)
draw_clear_alpha(make_color_hsv(0,0,2),0)
surface_reset_target()*/
//if surface_exists(global.surf3) surface_free(global.surf3)
//global.surf3=surface_create(room_width*3,room_height*3)
/*surface_set_target(global.surf3)
draw_clear_alpha(make_color_hsv(0,0,2),0)
surface_reset_target()
surface_set_target(surf1)
draw_clear_alpha(make_color_hsv(0,0,2),0)
screen_redraw()
surface_reset_target()
tile_layer_hide(1000)
tile_layer_show(1002)
tile_layer_hide(1000000)
surface_set_target(global.surf3)
draw_clear_alpha(make_color_hsv(0,0,2),0)
draw_set_color(make_color_hsv(0,0,2))
draw_set_alpha(0)
draw_rectangle(0,0,room_width*3,room_height*3,0)
draw_set_alpha(1)
draw_surface_ext(surf1,0,0,3,3,0,c_white,1)
surface_reset_target()
instance_activate_all()

background_showcolor=1
view_enabled=1
view_visible[0]=1
surface_free(surf1)
set_automatic_draw(true)
}*/
