nothing=0
if nothing=1 {
tile_layer_show(1000)
tile_layer_hide(1010)
tile_layer_show(1000000)
background_showcolor=0
set_automatic_draw(false)
instance_deactivate_all(true)
view_enabled=0
view_visible[0]=0
draw_clear_alpha(make_color_hsv(0,0,2),0)
screen_refresh()
draw_clear_alpha(make_color_hsv(0,0,2),0)
surface_set_target(global.surf2)
draw_clear_alpha(make_color_hsv(0,0,2),0)
screen_redraw()
surface_alpha()
surface_reset_target()
surface_set_target(global.surf3)
draw_clear_alpha(make_color_hsv(0,0,2),0)
draw_surface_ext(global.surf2,0,0,3,3,0,c_white,1)
surface_alpha()
surface_reset_target()
surface_free(global.surf2)
global.surf2=surface_create(room_width*3,room_height*3)
surface_set_target(global.surf2)
draw_clear_alpha(make_color_hsv(0,0,2),0)
surface_alpha()
surface_reset_target()
view_enabled=1
view_visible[0]=1
set_automatic_draw(true)
instance_activate_all()
draw_clear(c_black)
screen_refresh()
tile_layer_hide(1000)
tile_layer_show(1010)
tile_layer_hide(1000000)
background_showcolor=1
}
